### ISSUE TITLE
The Single file executale dont work

### ISSUE THREAD

**Issue by mdudek** [jsreport/jsreport#1037]
I have just tried to use 'Single file executable' approach. 
The execution of jsreport.exe simple do nothing. No result, no error. 

Followed instructions from https://jsreport.net/learn/single-file-executable
Tested on version 3.10.0, Windows 11 OS.

**Comment by pofider** [comment]
The folder where you run `jsreport.exe` is empty? Isn't the app blocked by antivirus?
I've tried windows 10 as well as fresh new windows 11 in VM, and this is the output

![image](https://user-images.githubusercontent.com/2041960/222891102-99e0f907-82fb-4d1f-b0ad-13ccef142e9e.png)

**Comment by mdudek** [comment]
I have tris to run it on hyper-v Win 11 image and it works as expected. Don't know why its not working on my local Windows. I have tried to disable all potential blockers (Defender/firewall), but still not working. Checked also system event log. there is nothing interesting.

**Comment by mdudek** [comment]
Just found a reason of the issue. I have compiled jsreport.exe myself and it's also failing on my machine. There is used forked 'bjrmatos/pkg' package for app compilation, but when I tried to use original vercel/pkg for compilation, it works without problem.

**Comment by bjrmatos** [comment]
@mdudek we use a fork of the pkg because we needed some patches in the compilation process to help with the size and other things. however this was checked and verified a long time ago, we have not tried the latest vercel/pkg, perhaps it already handles some things for us, but the current way we compile is tested on each release and so far we have not had any problems with it, perhaps there is other reason for it to not working on your windows machine.

anyway, we review the vercel/pkg changes from time to time, we will check in the future if our fork is still needed
