### ISSUE TITLE
child templates with FOP

### ISSUE THREAD

**Issue by michelre** [jsreport/jsreport#104]
I'm currently using FOP as a recipe for my templates. My templates became very very big and I needed a way to solve this issue. So I found the child template extension and it could have solved my problem. But to define my child templates with FOP, I needed a way to render them as XML. 

So I thought about a new recipe named 'identity'. This recipe does not do something crazy and it just renders the content of the template without any transformation (f(x)=x). It looks useless but it solves my issue. So maybe it could be useful to you and I wanted to share it with you. So I publish it to npm https://www.npmjs.com/package/jsreport-identity.

**Comment by pofider** [comment]
I am very happy you were able to implement an extension and even published it to public. I really appreciate this and hoping more people will start doing this.

Did you try to use `html` recipe instead of your `identity`? It basically does the same thing you implemented and only adds http headers to the response. So it should do the same job for you. Or am I missing something?

**Comment by michelre** [comment]
Yes I've just tried and it works too. I thought about using it but I was convinced that it was too specific. So it works pretty good with html and I think I'm gonna use it. ( :( I was so happy of publishing my first extension...)

Bottom line, I'm very fond of your project. First because it solves many issues that I haven't solved with other tools like jaspersoft. And second because it is in JavaScript and I'm a big fan of this language. So I understood that this project represents a lot of work for you and I would be glad to assist you.
