### ISSUE TITLE
Two prototype pollution vulnerabilites identified using snyk tool

### ISSUE THREAD

**Issue by vinayakshenoy91** [jsreport/jsreport#1042]
Two prototype pollution vulnerabilites identified using snyk vulnerability management tool. npm audit still shows as zero. This is also present in jsreport-core 3.10.0

1) Vulnerability introduced through **lodash.set** library:
Vulnerability | CWE-1321 | CVSS 7.3
Introduced through: @jsreport/jsreport-core@3.9.0 > **lodash.set@4.3.2**
**Remediation suggested: none**

<img width="629" alt="Screenshot 2023-03-16 at 7 12 25 PM" src="https://user-images.githubusercontent.com/21362332/225642291-6d1c69f2-f9a5-4937-af13-118f4511f85b.png">

<img width="645" alt="Screenshot 2023-03-16 at 7 12 42 PM" src="https://user-images.githubusercontent.com/21362332/225642344-a3e0f368-35c8-4cc0-af36-8c4eba4a9542.png">

2) Vulnerability introduced through **unset-value** library:
Vulnerability | CWE-1321 | CVSS 7.5 
Introduced through:  @jsreport/jsreport-core@3.9.0 > **unset-value@1.0.0**
**Remediation suggested: Upgrade unset-value to version 2.0.1 or higher.**

<img width="659" alt="Screenshot 2023-03-16 at 7 13 27 PM" src="https://user-images.githubusercontent.com/21362332/225642808-c8605b72-0862-4485-921b-5e9a8c6b10a2.png">

<img width="631" alt="Screenshot 2023-03-16 at 7 13 38 PM" src="https://user-images.githubusercontent.com/21362332/225642826-1142326b-fdf4-47b6-86d0-545d804b3157.png">

**Comment by bjrmatos** [comment]
hi @vinayakshenoy91 thanks for opening the issue. 

while true that the two vulnerability exists on those two packages which we use, it does not affect jsreport directly, because those two packages are used to execute internal logic, it is not exposed to user code, so the vulnerabilities does not present an issue for us because we execute the code that use the two packages in a safe manner.

we have verified that there is no vulnerability for us, so we are going to close this, thanks for making us aware of it.

we will keep track of `lodash.set` and update it when there is update available, just to prevent that jsreport appear in these vulnerabilities reports
