### ISSUE TITLE
Consider switching to isolated-vm in favour of vm2

### ISSUE THREAD

**Issue by m0ddixx** [jsreport/jsreport#1077]
Hello,
as per https://github.com/patriksimek/vm2 the project is discontinued and given its recent vulnerabilities it should be a wise choice to switch to the recommended isolated-vm

Are there any plans on tackling this problem or is any help needed?

**Comment by pofider** [comment]
Yes, thank you. We will analyze if it is possible to migrate.

**Comment by oxeye-gal-katz** [comment]
Any news on this issue?

**Comment by pofider** [comment]
We are currently fully working on replacing the vm2-based sandboxing. We have a prototype using [SES](https://github.com/endojs/endo/tree/master/packages/ses) which we further develop.
We want to have this ready before 5th September when the vm2 security leaks should be revealed.
See the progress in this branch https://github.com/jsreport/jsreport/tree/ses

Note that 95% of the jsreport installations don't use sandboxing and the vm2 dependency.  It is only used when you set in jsreport config `trustUserCode:false`. This means if we just remove vm2 from dependencies, the vast majority of the installation won't be affected. Anyway, we are working hard to keep sandboxing feature working just with a different approach.
However, if you now rely on `trustUserCode:false`, because you expose jsreport to external users and let them modify templates, you should consider adopting jsreport [docker-workers extension])(https://jsreport.net/learn/docker-workers).

Sidenote. We rejected isolated-vm package because its approach doesn't fit us. The isolated-vm is basically an extra embedded v8 without support for nodejs-specific things and support for importing modules. And we need to run in sandbox a lot of things including modules and nodejs-specific stuff. Also, the isolated-vm project status doesn't look future promising.

**Comment by pofider** [comment]
jsreport v4 now doesn't use vm2
https://jsreport.net/blog/jsreport-400-release
