### ISSUE TITLE
Recipe 'xlsx' not found

### ISSUE THREAD

**Issue by jfreak53** [jsreport/jsreport#109]
I have a strange problem. I am allowing my users of a reporting system to have access to both PDF and XLSX export formats. It works fine but for one tiny problem.

If the first report I run after starting the node server `node index.js` is a PDF report, then the excel report only kicks back this error:

```
Error during rendering report: Recipe 'xlsx' not found
```

However if I run the excel report first, then run the pdf then the excel again, no errors. It only happens if after starting the node server the first report is PDF instead of Excel.

Any ideas why this is and how to stop it? If I run the excel first every time after start the error never comes up, so I know the excel plugin is working.

**Comment by pofider** [comment]
You should use `jsreport.renderDefaults.extensions.push("xlsx");` before the first rendering call. This is because jsreport uses a singleton which is initialized just once based on `jsreport.renderDefaults` and this happens during the first `render` call.

If this doesn't help, please share your code sample.

**Comment by jfreak53** [comment]
Found it! Thanks! I had that there but it was behind an IF statement, so it was calling the first time around as per what it needs. Ok, all working now, thanks!
