### ISSUE TITLE
Getting error "Report cancelled by the client or closed network"

### ISSUE THREAD

**Issue by AaronI3** [jsreport/jsreport#1097]
After updating from version 2.6.1 to 3.13.0, we are getting the error below for longer running reports:

Error
![image](https://github.com/jsreport/jsreport/assets/138686634/1d64bc96-b99d-447a-b4d9-1c47e83f9839)

Config file
```
{
  "httpPort": 5488,
  "store": {
    "provider": "fs"
  },
  "blobStorage": {
    "provider": "fs"
  },
  "logger": {
    "console": {
      "transport": "console",
      "level": "debug"
    },
    "file": {
      "transport": "file",
      "level": "info",
      "filename": "logs/reporter.log"
    },
    "error": {
      "transport": "file",
      "level": "error",
      "filename": "logs/error.log"
    }
  },
  "trustUserCode": true,
  "reportTimeout": 120000,
  "enableRequestReportTimeout":true,
  "workers": {
    "numberOfWorkers": 2
  },
  "extensions": {
    "authentication": {
      "cookieSession": {},
      "admin": {
        "username": "username",
        "password": "password"
      },
      "enabled": false
    }
  }
}
```

**Comment by pofider** [comment]
This error signals that the client actually closed the connection so you should look at the caller code if it has properly configured timeouts.

**Comment by AaronI3** [comment]
@pofider We added the timeout to the client side for 120000. After updating from version 2.6.1 to 3.13.0 the time it takes has greatly increased. We imported the report from the server running the 2.6.1 version, so nothing changed on that end. We ran the report just now on the 2.6.1 server and it took 45 seconds. The 3.13.0 server is timing out at 120000. We have attached a log of the 3.13.0 server. 
[qc-sheet (1).txt](https://github.com/jsreport/jsreport/files/12621788/qc-sheet.1.txt)

**Comment by pofider** [comment]
It seems client or a proxy on the way closes the connection after 1 minute.

Based on the logs, I see that the rendering spends all time in chrome.
Unfortunately, the chrome performance fluctuates with version and it may perform worse with the later versions.
We need to update chrome because of security so there is not much we can do there.

You seems to be embedding quite some images. Do you use the images with proper size?
https://jsreport.net/learn/chrome-pdf#images-increasing-pdf-size

Can you try to disable the accessibility tags?
https://jsreport.net/learn/chrome-pdf#aria

**Comment by AaronI3** [comment]
Thanks @pofider, we edited our NGINX config file to change the timeout from 60 seconds to 300 seconds. This worked but the report was taking 2 minutes to complete. We then tried disabling the accessibility tags and this reduced the time taken from 2 minutes to 11 seconds.

**Comment by pofider** [comment]
Thanks for sharing. Can this be closed now?

**Comment by AaronI3** [comment]
Yes, thanks for the help
