### ISSUE TITLE
docx: Add attribute to all docx helper - "enabled" 

### ISSUE THREAD

**Issue by benben-user** [jsreport/jsreport#1109]
Currently we need to use external condition using handlebar to remove a table / list / html 
The FR is to add another attribute "enabled" : a condition for remove the "element" entirely.
(Same as you added to docxImage : failurePlaceholderAction and docxWatermark : enabled )

for me most relevant is to remove table if provided list is empty

**Comment by pofider** [comment]
Thank you for the FR.

Currently, we don't plan to add extra options for things that can be solved with standard conditions.
The image is a different case because the developer doesn't know if a remote image exists or not.

We value your feedback and we will reconsider the decision here when we see it's a mainstream problem that makes the most of the templates too verbose.
