### ISSUE TITLE
Multiple scripts per template

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#115]
It should be possible to run multiple scripts (from scripts extension) per single template.

**Comment by jcfergus** [comment]
Just wanted to +1 this.  Would be very helpful for some of my use cases.

**Comment by pofider** [comment]
@jcfergus Do you have any specific requirement for it?

The basic implementation should basically support just adding multiple scripts into the template and run them in the particular order.

**Comment by jcfergus** [comment]
Yeah, that's basically what I'm thinking - basically I want to have several scripts, each which read things from an API, and be able to easily wire multiple datasets from the API into one report without having to either do sub templates or combining the scripts into one.  

The only other thing I can think of might be the ability to specify what the object that each script should place into request.data would be called - i.e. 

DataType1Script:type1records
DataType2Script:type2records

Then pass that name into the script, so that when DataType1Script is run, it receives a parameter of "type1records" and knows to put its data into 'request.data.type1records', etc.  That might be overthinking it, though.

**Comment by pofider** [comment]
Thanks...

And how would you like to provide such an information to the script? You could provide this through API call in the `options` property and the script could read it from `request.options`. This should already work. Isn't this enough?

**Comment by bjrmatos** [comment]
> The only other thing I can think of might be the ability to specify what the object that each script should place into request.data would be called - i.e.
> 
> DataType1Script:type1records
> DataType2Script:type2records

@jcfergus i think you are overthinking it.. just treat it like express where all middleware can put data in `req` object, specific middleware can access this data explicitly calling `req.data.someData`, you just have to decide the shape of the object.

**Comment by pofider** [comment]
I have this already implemented here https://github.com/jsreport/jsreport-scripts/issues/1

After some testing it will be included in the next release.

**Comment by pofider** [comment]
Release in 0.11.0

**Comment by bjrmatos** [comment]
cool!! i will play with this really soon
