### ISSUE TITLE
External desktop editor integration

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#118]
Developers should be able to use their favorite desktop editor to develop templates. jsreport can listen to changes in the files and automatically preview reports.

**Comment by bjrmatos** [comment]
great! we also have to discuss the desktop version of jsreport studio :)

**Comment by pofider** [comment]
This should be implemented as a new extension probably named **jsreport-external-editor**

The extension should get the directory path from the jsreport configuration file during the initialization. If the directory is specified it should watch for changes in this directory. When a file is modified it should try to match the file with the existing jsreport template name. If it is found it should use something like socket.io to notify jsreport studio to preview the template. With this workflow the developer can use his favorite editor on one screen and immediately see the report preview on the another screen.

The extension should probably update the template inside the storage right away during previewing so no more synchronization is needed. This could be configurable.

It can support also helpers in the separate file with specific format like templatename_helpers.js or input data in templatename_data.json

Please join the discussion here when having a suggestion or a specific requirement. Especially @bjrmatos opinion is welcome here.

**Comment by bjrmatos** [comment]
sounds great to me!

what do you think about a workflow without template storage? i see use cases where storing the template is not important (and innecesary), because the single source of truth will be the templates directory.. the beauty of jsreport is that we can use web technologies (plain text files html/css/js) to develop reports, which enable us to handle version control easy because reports are just plain text files, but unfortunately handle version control currently is not nice because templates are inside json files (or database). **play nice with version control systems should be our priority!**

another option will be always replace what is in storage with the template's file content during initialization

to me, **supporting a workflow without storage should be the default, and storing the template (inside of json or database) only an option**.

also i think we should support a desktop version of jsreport studio (initially only the preview feature), this will allow to the developer create templates and preview instantly without open a web page, a closer experience to solutions like crystal reports, etc. maybe you can open another issue for discussion?

**Comment by pofider** [comment]
I would also love to have plain files with just html content, but we still need to store somewhere many other attributes. Common template contains many required attributes like content html, javascript helpers, engine type, recipe type, size, header, header size, sample data specification, name. I was thinking about this many times and even again during this issue, but didn't find a concept I am comfortable with. 

What would you propose? 

Maybe split every template into 3 files like this?
templatename.html - template content
tamplatename.js - template helpers
templatename.json - other template settings for recipe or engine, maybe yaml would fit here more

**Comment by bjrmatos** [comment]
what do you think about something like this?

<img width="272" alt="captura de pantalla 2015-10-13 a las 11 05 05 p m" src="https://cloud.githubusercontent.com/assets/4262050/10474652/e0f69932-71fe-11e5-8a8a-ab7632c645d4.png">

where `template.html` could be `template.jade` or `template.handlebars`, the name of the file would need to be `template` but the extension could be anything

instead of json for configuration we can use javascript so we have full power to make conditions based on environment in the configuration.

config.js
```js
var recipe = 'wrapped-html';

if (process.env === 'production') {
  recipe = 'phantom-pdf';
}

// configuration
module.exports = {
 ...
 recipe: recipe
 ... // and other options
}
```

**Comment by pofider** [comment]
Great, I see we will get to the concept worth it to implement.

1. folders for templates
Yes, this sounds better than prefixing the template name. OK

2. template content file extension
Ok, technically every extension including engines can listen insert/update and modify the file extension.

3. config.js
The dynamic config is nice, however I see some complications with that. 
Loading such a dynamic config is easy, however how to update/save it programatically? Saving from jsreport studio would overwrite the dynamic code. Basically every possible automation would not work. Like adding an attribute to all templates or updating all templates at once... 

It looks to me rather that template config represents a static metadata which should be stored in static form. Changing the recipe or any other required behavior based on dynamic condition can be easily implemented with jsreport extension.

Not a final word, go ahead and convince me. :)

**Comment by bjrmatos** [comment]
you're right.. if configuration is a js file would make integration with jsreport studio harder.

we should allow the configuration to be in json or yaml, the developer would choose what it feels more comfortable.

**jsreport-external-editor** would need to exist? or we should modify the extension that powers jsreport studio to meet this new behaviour? (i like the second option).

storing the template content and configuration would need to be another extension? or just a new config in global jsreport config?

**Comment by pofider** [comment]
I started the implementation of the template persistence we agreed on, the prototype should be ready today.

**Comment by pofider** [comment]
The first implementation is done, check it out in the repo [jsreport-fs-store](https://github.com/jsreport/jsreport-fs-store)

It supports basically everything we agreed on except the yaml. It also includes the studio automatic "live on change preview."

I will keep this as an opt-in option for a while and later I would like to deprecate the current default storage and replace it with this one.

**Comment by bjrmatos** [comment]
great! i will play with it and let you know if i have some comments!

**Comment by bjrmatos** [comment]
it works!

later (when template storage is an opt-in) we should extract metadata (modificationDate, version, etc) from config.json and store somewhere else in order to make it transparent files in version control systems.

if you try to use jsreport-fs-store in a custom express app

like this one:

```js
'use strict';

var app = require('express')();

var PORT = process.env.PORT || 4800;

require('jsreport').bootstrapper({
  express: {
    app: app
  }
}).start().then(function() {
  app.listen(PORT, function(err) {
    if (err) {
      console.error(err);
      throw err;
    }

    console.log('Report Server STARTED on:',
      this.address().address + ':' + this.address().port
    );
  });
});
```

the socket.io connection (from jsreport-fs-store) will fail

<img width="1305" alt="captura de pantalla 2015-10-17 a las 6 47 43 p m" src="https://cloud.githubusercontent.com/assets/4262050/10561798/11d5699e-7500-11e5-8767-2213b0a1a3bc.png">

because `reporter.express.server` is undefined and socket.io (server part) never attaches to a server

jsreport-fs-store/lib/main.js
```js
reporter.initializeListener.insert({after: 'express'}, 'fs-store', function () {
        // in a custom express app reporter.express.server is undefined
        var io = IO(reporter.express.server);

        reporter.documentStore.provider.on('external-modification', function () {
          io.emit('external-modification', {});
        });
      });
```

i thought that making `reporter.express.server` a server instance comming from the custom app would be enough but now i'm getting other error.

<img width="974" alt="captura de pantalla 2015-10-17 a las 7 36 06 p m" src="https://cloud.githubusercontent.com/assets/4262050/10561911/59d74e28-7506-11e5-9255-820ba2cd0a72.png">


changes i made:

**jsreport/extension/express/lib/reporter.express.js**
```js
if (definition.options.app) {
            reporter.logger.info("Configuring routes for existing express app.");
            configureExpressApp(app, reporter, definition);

            if (definition.options.server) {
                reporter.logger.info("Using existing server instance.");
                reporter.express.server = definition.options.server;
            }

            logStart();
            return;
        }
```

**custom app**

```js
'use strict';

var http = require('http'),
    app = require('express')();

var PORT = process.env.PORT || 4800;

var server = http.Server(app);

require('jsreport').bootstrapper({
  express: {
    app: app,
    server: server
  }
}).start().then(function() {
  server.listen(PORT, function(err) {
    if (err) {
      console.error(err);
      throw err;
    }

    console.log('Report Server STARTED on:',
      this.address().address + ':' + this.address().port
    );
  });
});
```

any idea?

**Comment by bjrmatos** [comment]
ok, the "Converting circular structure to JSON" error happens because /api/extensions tries to serialize the `reporter.extensionsManager.availableExtensions` array, when it encounters with the express instance it fails

**Comment by bjrmatos** [comment]
this could be easily fixed if delete the `server` option after set `reporter.express.server`

**jsreport/extension/express/lib/reporter.express.js**
```js
if (definition.options.app) {
            reporter.logger.info("Configuring routes for existing express app.");
            configureExpressApp(app, reporter, definition);

            if (definition.options.server) {
                reporter.logger.info("Using existing server instance.");
                reporter.express.server = definition.options.server;
                // deleting option to avoid error in JSON.stringify from req.json
                delete definition.options.server;
            }

            logStart();
            return;
        }
```

let me know if you are ok with this, i have a PR for jsreport-fs-store to check if `reporter.express.server` is undefined

**Comment by bjrmatos** [comment]
with those changes, i have jsreport-fs-store working in a custom express app :smiley:

**Comment by pofider** [comment]
OK, thanks. You can PR those changes.

The same folder structuring already works for scripts and sample data items. 

It is true that every template editing from the studio causes update of `modificationDate` and therefore a modification entry of `config.json` in the source control. Not sure if it is a big deal. The separation of it somewhere else doesn't look to me to be worth it, I would rather remove that attribute.

The `version` attribute should not be there, it is a bug. The other attributes could stay in the `config.json` I think. However you should be able to have the rendering and API working right now with just following config.json
```js
{
    "name": "Sample report",
    "engine": "handlebars",
    "recipe": "html"
}
```
Then the request `POST api/report { template: { name: 'Sample report' } }` should work.

We will likely need to provide a migration utility when is this released as default. Therefore I would like to have this in as much final form as possible. You can fill additional requirements directly to the [jsreport-fs-store](https://github.com/jsreport/jsreport-fs-store).

**Comment by bjrmatos** [comment]
> The same folder structuring already works for scripts and sample data items.

great! i didn't realize that



> It is true that every template editing from the studio causes update of modificationDate and therefore a modification entry of config.json in the source control. Not sure if it is a big deal. The separation of it somewhere else doesn't look to me to be worth it, I would rather remove that attribute.

i think when template storage is an opt-in we should remove `modificationDate`, since it will be not necessary



> We will likely need to provide a migration utility when is this released as default.

you're right, a migration utility would be necessary

i will send a PR and i think this feature will be done

**Comment by pofider** [comment]
I think we are done with this.

**Comment by bjrmatos** [comment]
@pofider FYI [jsreport-migrate](https://github.com/bjrmatos/jsreport-migrate) is published, try it out with `npm install -g jsreport-migrate`, `cd /your/legacy-jsreport-project`, `jsreport-migrate` see the magic 😄 

i didn't consider some things (schedules, tasks) for the migration tool, but easily solved with a PR, i have tested the migration tool in a project used in production and it works perfectly! let me know your feedback!

**Comment by bjrmatos** [comment]
![migration](https://cloud.githubusercontent.com/assets/4262050/16475326/22e36d50-3e43-11e6-96c3-31158c86b09e.gif)
