### ISSUE TITLE
PDF/UA performance with img tag in header

### ISSUE THREAD

**Issue by jorisdebock** [jsreport/jsreport#1190]
I noticed when I enable pdf/ua the pdf generation takes a long time when including an image in the header.

Could this be improved?

pdf with 10 pages more or less plain text

header-footer.pdf

```
<html>
    <body>
        {{for $pdf.pages}}
          {{if ~#index}}
            <div style="page-break-before: always;"></div>
          {{/if}}
        <main>
            <header>
                <img height="60" src="{#asset /pdf/__layout/v1/images/logo.png @encoding=dataURI}" alt="abc" />
            </header>
            <footer>
                abc
            </footer>
        </main>
        {{/for}}
    </body>
</html>
```

with img tag in header
```
debug +0 pdf-utils postprocess start
debug +5839 pdf-utils postprocess end
```

without img tag in header OR with pdf/ua disabled
```
debug +0 pdf-utils postprocess start
debug +14 pdf-utils postprocess end
```

It takes about 5-6 seconds more when img tag in header and pdf/ua enabled

**Comment by pofider** [comment]
Thanks. We will look if some kind of local cache won't help here.

**Comment by pofider** [comment]
I get 150ms of pdf utils postprocess for 100 pages and [100kb image](https://jsreport.net/screenshots/studio.png?v=1).
Could you share the image you are merging in the header?

**Comment by jorisdebock** [comment]
I was checking what is causing the extra time and seems to be caused by pfdA processSMask, If you want I can create a PR to improve the perf of that method.

this is the image we are using in the header
![hn_logo](https://github.com/user-attachments/assets/c0443a06-0464-4e40-9b7c-73f2cbf82218)

**Comment by pofider** [comment]
Yes, I was expecting this would be the bottleneck. Nice optimization in https://github.com/jsreport/jsreport/pull/1191 thank you.

While checking on this, I found out that since version 122, chrome doesn't reference duplicated images but instead always embeds new streams. In other words, before, 100 pages pdf with header image, would have in pdf just one image embedded, while now it has 100 images in the pdf. Trying to find some notes about this in chromium change log, but no luck so far.
