### ISSUE TITLE
Pdf concatenation

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#122]
Implement extension or recipe capable of joining multiple pdf reports into one. This bring us possibility to have different page sizes and different header sizes across the single pdf report.

**Comment by bjrmatos** [comment]
seems [possible](http://stackoverflow.com/questions/25640533/pdfkit-nodejs-merging-two-pdf-files) with [pdfkit](http://pdfkit.org/).. (but i need to test if it works on node v4) i will search more options

**Comment by pofider** [comment]
First we need a proof of concept that pdf concatenation works on both linux and windows.

Then we can discuss how to provide concatenation through jsreport.

**Comment by pofider** [comment]
Unfortunately I was not able to make pdf merge working with pdfkit. It is likely that it is [not supported](http://stackoverflow.com/questions/32215924/nodejs-pdfkit-how-to-merge-two-pdfs). 

I have done some research but found nothing suitable. There doesn't seems to be a suitable native javascript library or a node.js package supporting this. 

There are many libraries in other languages or platforms but this would require complicated installation to have it working cross platform.

Maybe a native nodejs package would be a solution, but I have no experience with that.

**Comment by bjrmatos** [comment]
i will try to search (and try) other options, in the worst case we could leave this improvement for the last

**Comment by MI53RE** [comment]
Hi Jsreport team!
Just wanted to now if there was any update regarding this subject?
If not, I did some research on my side and so far the "most-recommended" package that I did found was [pdf-merge ](https://github.com/wubzz/pdf-merge) which depend on [pdftk](https://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/) so we are, again, depending on a third party software but I still though this could be good to share it here too (until you find a way to integrate the feature into jsrport which would be awesome!)

**Comment by MI53RE** [comment]
Hi Jsreport team!
Just wanted to now if there was any update regarding this subject?
If not, I did some research on my side and so far the "most-recommended" package that I did found was [pdf-merge ](https://github.com/wubzz/pdf-merge) which depend on [pdftk](https://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/) so we are, again, depending on a third party software but I still though this could be good to share it here too (until you find a way to integrate the feature into jsrport which would be awesome!)

**Comment by bjrmatos** [comment]
hi @MI53RE so far we have not looked more into this subject.

thnks for the mention of `pdftk` (and it seems that it is cross-platform, so great!), we will have that tool in mind when coming with a solution for pdf concatenation.

if you are currently needing this, you can experiment doing an extension, just to prove that it works great, if the experiment works great maybe there's a chance to include it as an official extensions 😀

**Comment by bjrmatos** [comment]
hmm seems that `pdftk` needs to have some license to be able to distribute it in another application, it that is the case i fear that it would need to stay as a third-party extension

**Comment by MI53RE** [comment]
@bjrmatos Awweee didn't see that part, what a shame :(
Anyway I'll still try to make it work and give you the result!

**Comment by MI53RE** [comment]
Hi Jsreport team!
just to tell you I found a way to do it properly and EASYLY (even more than with pdftk that I mentioned before!) `pdfunite` from `Poppler`! and actualy some people were kind enough to compile the binary for windows, therefore it can be used on (probably) every operating system as of now :D

Licence is [GPL v3](https://en.wikipedia.org/wiki/GNU_General_Public_License#Version_3)
[wiki(software)](https://en.wikipedia.org/wiki/Poppler_(software))
[Poppler](https://poppler.freedesktop.org/)
[Poppler for windows](http://blog.alivate.com.au/poppler-windows/)

Once I'll be done with the connector I'll come back here to let you know: little question: is it possible to include linux/mac binary within an app rather than having them installed?

**Comment by pofider** [comment]
I'm afraid that GPL license means that every software which consumes the lib needs to be open sourced. We cannot use such licensed software in our official distribution, however there is no harm to release custom extension with GPL license.

Note that GPL open sources restrictions doesn't cross the http request call boundary. Which means that you can use jsreport with such extension without opensourcing your commercial product as long as you communicate with jsreport through http and doesn't link it to your application directly.

**Comment by MI53RE** [comment]
Ha I see, seems that won't do to be part of the official extension indeed.
Anyway thank you very much for that clear explanation!! Also that did save me from doing a BIG mistake since I was calling it from command line, which (if I get it right) would have forced use to make the whole product open sourced too. Anyway I will oriente that extension to be callable throught http and if you still want it as an 'unofficial-workarround-extension' I will share it :)

**Comment by pofider** [comment]
Not sure if command line call fits to the GPL boundary or not, you should double check it, may be it is allowed. And sure, every custom extension is more than welcome.

**Comment by pofider** [comment]
We were able to implement the pdf concatenation and merging using native javascript. 
See this announcement about the new very powerful extension
https://jsreport.net/blog/merge-and-concatenate-pdfs

**Comment by MI53RE** [comment]
Wow!! That's awesome! A big thanks to you guys! :D
