### ISSUE TITLE
Pdf Recipe: [Error: Error during rendering report: stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by paulJordaan** [jsreport/jsreport#180]
I'm getting the following error when using the Phantom PDF recipe:

[Error: Error during rendering report: stdout maxBuffer exceeded

It only happens when rendering big reports. Is there a way to increase the buffer size?

**Comment by pofider** [comment]
Which jsreport version you have? Can you give us the whole stack trace? It should be included in the error.log.

Since jsreport@0.13 we transfer all the `console.log` messages from phantomjs for better debugging and I have a suspicion this can be causing this error. I created issue to solve this https://github.com/pofider/phantom-html-to-pdf/issues/25 
Can this be the problem? To workaround it currently you can try to remove some console.log calls from your template or try to change configuration option { phantom.strategy = 'phantom-server' } which should be able to transfer more.

**Comment by paulJordaan** [comment]
I'm using version 0.12

The following is the stack trace:

2016-02-24T22:03:20.186Z - error: Error during processing request: http://myserver/api/report details: Error during rendering report: stdout maxBuffer exceeded Error: stdout maxBuffer exceeded
    at Socket.<anonymous> (child_process.js:266:14)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
From previous event:
    at /home/vcap/app/node_modules/jsreport/node_modules/jsreport-core/lib/render/render.js:141:54

**Comment by pofider** [comment]
Are you sure about the version? There is no such a line in 0.12
`at /home/vcap/app/node_modules/jsreport/node_modules/jsreport-core/lib/render/render.js:141:54`

Also, the html recipe works? Do you have any scripts attached? Do you use `console.log` somewhere in the helpers/template? Did you try to switch the strategy as I recommended?

**Comment by paulJordaan** [comment]
Apologies, I am running version 0.13.1.

Changing the strategy seems to have fixed the problem. 

Is it possible to change the resourceTimeout setting (https://github.com/pofider/phantom-html-to-pdf/issues/7) for phantom inside prod.config.json?

```
"phantom": {
     "timeout": 180000,
        "strategy": "phantom-server",
        "allowLocalFilesAccess": true,
        "settings": {
            "resourceTimeout": 18000
        }
    }
```

**Comment by pofider** [comment]
> Is it possible to change the resourceTimeout setting (pofider/phantom-html-to-pdf#7) for phantom inside prod.config.json?

Yes, that should work

**Comment by bjrmatos** [comment]
same problem for me trying to migrate from @0.9.1 to latest version @0.13.4, using `phantomjs`recipe and `dedicated-process` strategy.

The report is not big at all but the input for the report contain images encoded as base64 strings (a large chunk of string), when running with `dedicated-process` strategy jsreport only throws an error:

<img width="1902" alt="captura de pantalla 2016-05-25 a las 11 16 17 p m" src="https://cloud.githubusercontent.com/assets/4262050/15563500/b6cb41d6-22ce-11e6-95d8-c37ade82d3ae.png">

but using `phantom-server` strategy the report is generated but now we can see how a large chunk of string is printed in console/stdout, the funny thing is that this behaviour only occurs in the first render of the report, next renderings not print messages at all, i think this is because phantomjs saves the images in its cache.

first render:

<img width="1908" alt="captura de pantalla 2016-05-25 a las 11 18 10 p m" src="https://cloud.githubusercontent.com/assets/4262050/15563534/17d120ea-22cf-11e6-864f-ed6bbcf0a7f5.png">

second render:

<img width="1902" alt="captura de pantalla 2016-05-25 a las 11 21 49 p m" src="https://cloud.githubusercontent.com/assets/4262050/15563592/96208a44-22cf-11e6-9a2e-dafcba98ab3f.png">

i know that is a bad thing to pass images as base64 strings but i just wanna to report that a report running in an old version of jsreport may not work in latest jsreport.

**Comment by bjrmatos** [comment]
for clarification, the large chunk string printed to console are logs from `phantomjs` requests

**Comment by pofider** [comment]
Oh, images... I was thinking what could potentially cause this....

The solution is to trim the big messages coming from phantomjs  https://github.com/pofider/phantom-html-to-pdf/issues/25 

I'll patch this now into 0.13.5

**Comment by pofider** [comment]
jsreport@0.13.5 is published now including fix for this

**Comment by bjrmatos** [comment]
just to confirm, it works perfectly with the fix :smile:

**Comment by pofider** [comment]
Thanks for verification!
