### ISSUE TITLE
PDF preview in Chrome and Safari

### ISSUE THREAD

**Issue by carlskii** [jsreport/jsreport#195]
Hi,

I just installed jsreports, however the PDF preview section does not work properly using Chrome of Safari on the Mac. Firefox seems to work OK. 

Are there any known issues or limitations with these browsers. 

The download and preview are not available.

**Comment by bjrmatos** [comment]
it works for me on chrome 49 OSX Yosemite

<img width="1913" alt="captura de pantalla 2016-04-02 a las 12 20 14 p m" src="https://cloud.githubusercontent.com/assets/4262050/14228110/9513e948-f8d1-11e5-8d2d-b3293a424bea.png">

and safari 

<img width="1918" alt="captura de pantalla 2016-04-02 a las 12 52 25 p m" src="https://cloud.githubusercontent.com/assets/4262050/14228120/ce2b34c0-f8d1-11e5-880e-1b0ec24c55da.png">

**Comment by carlskii** [comment]
Can you also download and save the PDF ? It does also render for me, but I can't save to PDF.

**Comment by bjrmatos** [comment]
in chrome i can't save the PDF, you will need to send to print the PDF, and from there just save the PDF as file.

<img width="1912" alt="captura de pantalla 2016-04-02 a las 1 05 51 p m" src="https://cloud.githubusercontent.com/assets/4262050/14228182/b63627ec-f8d3-11e5-8cb9-fc86a3bcba4a.png">

in safari you'll need to click in the preview button and from there save the file

<img width="1911" alt="captura de pantalla 2016-04-02 a las 1 08 20 p m" src="https://cloud.githubusercontent.com/assets/4262050/14228200/431d8b78-f8d4-11e5-85c5-f87092603f3b.png">


i think that the reason for the download button is not working is because we're generating PDF on the fly, so there is no source for chrome/safari's PDF preview to download

**Comment by pofider** [comment]
You can also click "Run in new tab" and then save the whole page with ctrl+s to PDF
