### ISSUE TITLE
jsreport cli

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#219]
Might be a good idea to have an official command line api for jsreport provided as extra package

For start it should be able to render reports from command line,  something like

```
jsreport --request req.json --output out.pdf

# maybe also
jsreport --template.recipe electron-pdf --template.engine jsrender --template.content hello.html --output out.pdf
```

There are probably many other useful features this could bring...

Potentially, it could have capability to compress whole app into single running executable which would decompress itself during the first run. This could simplify the production deployments. 
Please let me know if anyone had positive experience with packing node application into single executable which would not require decompressing at the first run. All my attempts with virtualized file systems, electron, jxcore failed for running phantomjs in child process.

**Comment by jedibiddulph** [comment]
On the api command line call I feel the following would be useful . ( High )
--template.data  Path to json file which holds the data the report will use.
--template.helpers  path to a file of Java code which can be called.  Why we are likey to crate a standard code base and call them

Also if possible  (Low)
There are a number of setting you can pass these are available by passing a json object to the template some of these values may have value i.e paper size.

**Comment by jedibiddulph** [comment]
on a api This would only be needed by large customers (Low)
--server  Name/IPaddress

this would allow a command line to access another jsreport server and "outsource" the process, this is like the report service running but done in house. This is likely to be an "extra" modulo  and available at an extra cost as not needed by 90% of people but the 10% should pay for the extra service, and I feel $150 us would be a fair price for single user and $350 for enterprise.

**Comment by pofider** [comment]
I started to work on this and should have a prototype during the weekend.

And I got great idea regarding cli performance:
The first run of `jsreport --render ....` will create an extra node process where it initializes the jsreport and create a socket server. The original process then "remotely"  render the report there, output the result and exit. The extra node process will stay alive. Another call to `jsreport --render...` will reuse the previously created jsreport socket server to render. This will make cli performance usable.

**Comment by bjrmatos** [comment]
> The first run of jsreport --render .... will create an extra node process where it initializes the jsreport and create a socket server. The original process then "remotely" render the report there, output the result and exit. The extra node process will stay alive. Another call to jsreport --render... will reuse the previously created jsreport socket server to render.

that's exactly how [flow](https://flowtype.org/docs/new-project.html#using-the-flow-server) works and its a good idea :smile:

**Comment by pofider** [comment]
Additional analysis how this extension could fit to jsreport ecosystem.

How it could work from the end user perspective in different types of jsreport usages:

1. npm based installation of jsreport and then direct call to cli

```sh
npm install jsreport
jsreport render ...
```

2. `jsreport.exe` single executable cli

```sh
jsreport.exe render ....
```

3. Customized `jsreport-core` embedded in another application

```js
var jsreport = require('jsreport-core')()
jsreport.use(require('jsreport-cli')({
  entryPoint: "server.js"
))
jsreport.init()....
```

Then in cmd
```sh
jsreport render ....
```

4. Common jsreport installation

```sh
npm install jsreport
jsreport init
jsreport render
```

This is quite straight forward. The most problematic thing is to find out which script should be used to bootstrap jsreport:
- the entry point is passed through config to the extension
- the entry point is  set in the root `package.json` through `jsreport.entryPoint`
- the last default is to run `require('jsreport')().init()`

The command `jsreport` runs the entry point. This initializes the extension `jsreport-cli` which is responsible to deal with `process.args`.

The next topic is how the particular command like `render` should work. Here I see 3 different scenarios:

1. The cli initializes new jsreport and invokes `reporter.render`
2. The cli ensures there is jsreport server running and use REST API to call `/api/report`, it doesn't shut down the server afterwards and keeps it running for next call to optimize performance
3. The cli has a `serverUrl` parameter set and uses it to invoke REST API to render report

This is just rough idea for start...

**Comment by pofider** [comment]
It seems `jsreport-cli` could be installed also standalone and used to render reports in remote server.

```sh
npm install jsreport-cli
jsreport render --serverUrl=https://foo.jsreportonline.net --template=....
```

**Comment by bjrmatos** [comment]
some comments after taking a look at the implementation:

- in all diferent types of jsreport's usage i think we will need access to the instance created in the initialization process:

```js
/* Customized jsreport-core embedded in another application */
var jsreportInstance = require('jsreport-core')(/* user can have custom options here */)
jsreportInstance.use(require('jsreport-cli')())

if (require.main !== module) {
  /* we will need to educate our users, that in order to use jsreport-cli in its jsreport installation, they will need to export the jsreport instance */
  module.exports = jsreportInstance
} else {
  jsreporInstance.init().then(function() {
    console.log('jsreport started')
  })
}
```

the reason to need the jsreport instance is that the CLI will need to know when the instance is "ready", or it just will need it for launch the process by itself and know when its ready.

- "the entry point is passed through config to the extension" -> passing the entry point to the extension through config will not work, because at this point it is too late to use that option in CLI.

```js
jsreport.use(require('jsreport-cli')({
  entryPoint: "server.js"
))
```

order of execution:

- CLI command is executed (at this point the CLI will need to know which file should require)
- jsreport entry point executed (required by CLI, too late to pass entry point..)


at this point we are left with:

1.- the entry point is set in the root package.json through jsreport.entryPoint
2.- the last default is to run require('jsreport')().init()

since we will have the jsreport instance in CLI (always exported by entry file), maybe we can drop option 2. i can change `jsreport --init` command to generate the boilerplate code (`if (require.main !== module) {....}`) needed to export the jsreport instance.

comments?

**Comment by pofider** [comment]
> in all diferent types of jsreport's usage i think we will need access to the instance created in the initialization process...

Thinking if there is really no way how to get the jsreport instance without requirement for return. Isn't it like that the node.js requires `jsreport-cli` that requires bootstraping script and that requires back `jsreport-cli`? Which means we can share the instance through `jsreport-cli`?  The returning jsreport is also fine, just thinking if there is no easier solution.

> passing the entry point to the extension through config will not work

Yes I see, unfortunately.

> since we will have the jsreport instance in CLI (always exported by entry file), maybe we can drop option 2

I would like to keep the `2` because this is the important  use-case where we have no bootstrapping entry point. Like in single executable or if you just install jsreport and run `jsreport render`

**Comment by bjrmatos** [comment]
> I would like to keep the 2 because this is the important use-case where we have no bootstrapping entry point. Like in single executable or if you just install jsreport and run jsreport render

ok!, i will keep this default.


in `jsreport-cli` there will be two parts:

1.- `CLI part` (providing the jsreport command)
2.- `extension part` (with jsreport.config.js, index.js, etc), the idea was that the extension part will be responsible for handling `process.argv` parsing and processing, but i think that this should be the responsability of the `CLI part`, the extension part should be responsible for handling the registration and processing of new commands registered by other extensions (`jsreport-import-export`), this is just a rough idea, that probably will need some changes in `jsreport-core` and more deep thinking

i don't see how these two parts can communicate to each other without a returning jsreport instance from entry point, also the use of `require('jsreport-core').Reporter.Instance` feels wrong to me, using that will assume that user could only use one instance of jsreport per application, but i can think a scenario when user can easily just create two instances with different configuration (or just overriding some values in each instance), in that case what will be the value of `require('jsreport-core').Reporter.Instance`, the last one? 
(i think that there is nothing in jsreport that prevents the user to create two or more instances and i think that this is good because it let user to use jsreport in different ways that we can't imagine).

what i'm saying is that i think that the `extension part` is useless right now, at least if we want to start just with the most basic implementation and basic first class commands (`init`, `repair`, `render`).

**Proposal**

- in order to use `jsreport-cli` in a jsreport installation, entry points will always need to export a jsreport instance

- entry points will be determined by looking at `package.json` through `jsreport.entryPoint`, if not found the default is to run `require('jsreport')().init()` to get a jsreport instance

- `CLI part` of `jsreport-cli` will have first class commands (`init`, `repair`, `render`) and a special command called `commands`

- when using `$ jsreport commands` it will search all extensions (via `jsreportInstance.init()`) and list all the available commands found from extensions, the `commands` command is just for letting to know the user which commands from extensions they have available in its jsreport-distribution, later when the user already knows what commands they have available, they can directly call the desired command: `$ jsreport [insert your command from extension here] [options for command]`

- `extension part` of `jsreport-cli` will get somehow a `commandManager` object (from `CLI part`) to provide an interface to extensions that allows the registering of custom commands, one way to share the `commandManager` object will be assigning that object in the jsreport instance that we have in `CLI part` and in `extension part` just try to read that object.

```js
/*CLI PART of jsreport-cli*/
var commandManager = ....

var jsreportInstance = require(entryPoint)

jsreportInstance.commandManager = commandManager
```

```js
/*extension part of jsreport-cli*/

module.exports = function(reporter, definition) {
  if (reporter.commandManager == null) {
    /* do nothing since we are not running from a CLI */
    return 
  }
  
  var commandManager = reporter.commandManager

  /*create an interface/API based on commandManager for later use in other extensions*/
  reporter.addCommand = function(command, handler) {
    commandManager.option(command, handler)
  }
}
```

**Comment by pofider** [comment]
Ok, lets go that way. Just one note to back compatibility - you probably need to keep old the commands handling in `jsreport` package, so the the `node node_modules/jsreport --init` as well as `npm start --install` runs as previously. If it is not a big problem...

**Comment by pofider** [comment]
This is now finished. Thanks to @bjrmatos  for all his work on CLI

announcement
https://jsreport.net/blog/introducing-jsreport-cli

blog post
https://jsreport.net/learn/cli
