### ISSUE TITLE
jsreportonline images aren't saving

### ISSUE THREAD

**Issue by djangojack** [jsreport/jsreport#220]
Every time I try uploading and saving an image, it looks like this:

![screen shot 2016-06-10 at 1 07 00 pm](https://cloud.githubusercontent.com/assets/12073894/15972451/8b388ee4-2f0c-11e6-8cd3-ef267e053a1d.png)

**Comment by pofider** [comment]
Thank you, I was able to replicate it. The bug seems to pop up when clicking the save button.

Until we fix it, you should be able to upload new images just by clicking upload (don't hit save afterwards). To re-upload existing image, just click upload and then refresh the page (F5), again, don't hit save.

Sorry for the inconvenience

**Comment by djangojack** [comment]
Thanks. Any way to change the image name without clicking save?

**Comment by pofider** [comment]
Renaming the file to the desired name before uploading it should work.

**Comment by pofider** [comment]
This is now fixed in the next prepared jsreportonline release. See it here
https://jsreportonline-test.net
