### ISSUE TITLE
Servers cluster and synchronization

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#254]
The cluster of multiple jsreport servers currently requires having static templates or a store like mongodb. The static templates are sometimes not an option because developers wants to edit the templates right away in production environment. And database like mongo increases the maintenance as well as the costs of reporting solution.

Maybe it wouldn't  be too difficult to enable jsreport servers cluster to work also with file system store. This would require that servers knows about each other - this can be statically defined in the  config. Then all the updates would be captured with listener and broadcast to other servers. I know that there are problems with errors handling and servers failure, but maybe it is not so problematic and maybe we can be pragmatic here and reload all data in some cases.

This is just a feature suggestion...  I don't have plans for immediate implementation, but I think that every serious deployment plans 2 servers for high availability and this feature could save them a lot.

**Comment by bjrmatos** [comment]
i was thinking about this too, and when I read this [post](https://realm.io/news/first-object-database-realm-node-js-server/) I came up with an idea, maybe it will be possible to replace `nedb` with `realm`, according to the post `realm` can handle interprocess communication (write/updates) very well and have a feature called collection's notifications that can be used in favor of this feature.

I don't know too mucho about `Realm` yet but seems promising 😄

**Comment by pofider** [comment]
Thanks for this idea. I'll definitely evaluate deeply this. Originally I was thinking about replacing nedb with our full custom implementation but if there is something already working....

We probably need a custom persister to make sure templates are still nicely structured on the disk. Reloading on external changes. Mongo like API and synchronization across servers. We don't store millions of records, not sure if a native compiled c extension like realm is not an overkill for this.

Or do you think about `realm` as just another custom jsreport store, which would be used in this multi server environment but with different structure in the file system?

**Comment by bjrmatos** [comment]
> We probably need a custom persister to make sure templates are still nicely structured on the disk. Reloading on external changes.

just like `nedb` i think this can be handled in `realm` too, in fact since `realm` has built-in notifications, sync for external changes seems very approachable.



> Mongo like API and synchronization across servers.

you mean "across server processes (same app, multiple instances)" right? sync between different servers (in different machines) seems very problematic.



> We don't store millions of records, not sure if a native compiled c extension like realm is not an overkill for this.

`realm` was created as a mobile database, to replace something like `sqlite`, so i think `realm` was not built to handle millions of records, just to handle a number of records (hundreds/thousands) but to handle it correctly. Just an embedded database just like `nedb`.



> Or do you think about realm as just another custom jsreport store, which would be used in this multi server environment but with different structure in the file system?

maybe a first version of this idea can be published as another jsreport store implementation, just to experiment and see how it goes. but i was thinking in `realm` as an option in the official `fs-store`.





> Of course I don't know realm yet, but fighting with node-gyp errors now. :)

are you on Windows, right? 😆 yeah a bit problematic but i think it can work with solutions like node-pre-gyp

**Comment by pofider** [comment]
This is part of the new fs store rewrite so this issue is a duplicate
https://github.com/jsreport/jsreport/issues/333
