### ISSUE TITLE
Define and document structure of render pipeline req/res

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#262]
There are two main objects that flow from the rendering request pipeline.

`request` and `response` 

Some extensions expects these objects are express based instances, but this is not always true in `scheduling` or `cli` extensions.  There should be clear strict structure defined and documented.

**Comment by bjrmatos** [comment]
some comments about what i think it will be a nice structure for `request` and `response` objects in render pipeline:

right now the `request` object is our root of evil, simply because its structure and origin of the object is very different between rendering in a http context (starting a rendering from `/api/report` endpoint) and rendering from jsreport programatic API (calling `.render()` method).

## what we have currently in `request` object:

- when rendering from a http context the `request` object is a express request object and because of that there are extensions that are expecting the `request` object to be always a express http request object (they expect to find methods, properties like `.url`, `.originalUrl`, `.headers`, etc), or even worse there are some listeners in collections (`beforeUpdateListeners`, `beforeInsertListeners`, `beforeRemoveListeners`) that expect a request object in its function signature (though i don't know yet if some of those listeners expect to work with a express request object)

here is a list of extensions that expect a express request object or use a request object in listeners of collections:

https://github.com/jsreport/jsreport-assets
https://github.com/jsreport/jsreport-child-templates
https://github.com/jsreport/jsreport-images
https://github.com/jsreport/jsreport-import-export
https://github.com/jsreport/jsreport-public-templates
https://github.com/jsreport/jsreport-reports
https://github.com/jsreport/jsreport-resources
https://github.com/jsreport/jsreport-authorization
https://github.com/jsreport/jsreport-browser-client
https://github.com/jsreport/jsreport-scripts
https://github.com/jsreport/jsreport-templates
https://github.com/jsreport/jsreport-sql-store 
https://github.com/jsreport/jsreport-freeze

- when rendering from a module context (`.render()` method call) the request object will be the same object that user is passing to `.render()`, unfortunately since all extensions are using the request object as some kind of storage mechanism (containing value expected to be shared between extensions in render pipeline) the original object that the user has provided is modified in many places, also since we are using the same object that the user is passing we have a possible vulnerable scenario if the original object (from user) contains a special property that some extension is using, i think that the possibility that something like that could happen decreases the predictability of the system.


**the current structure of `request` (or at least the most used and present in the pipeline):**

`id`
`template`
`data`
`options` -> this property is kinda special because i thought that the values here should be the options passed from the user but actually there are extensions that are saving some values here (like setting `isChildRequest ` in phantom-pdf, jsreport-wkhtmltopdf)
`logger`
`startTime`
`reportCounter` (same as `id`) property
`reporter`
`toner` (present just for back compatibility i think) 

the properties names are very descriptive so i think i do not need to explain what they contain 😀

## my proposed structure for `request` object:

`template`
`data`
`options` -> this time options should be only values passed from user (not storing values assigned by extensions)
`logger`
**`context`** -> put in this object properties that are meaningful across extensions or that contain information about the context of the request (`id`, `reportCounter`, `startTime`, `isChildRequest ` or some new properties like `isHttp` or `httpRequest: real express request` to give some kind of hint to extensions that they are actually running in another context and they have the chance to run different code depending of the context if necessary) and it will be even better if we endorse that all extensions use this property (`.context`) as a namespace to share values instead of just adding properties to `request.template` sporadically (of course there are extensions that will need to replace values like `template.content` but that will be expected and ok but any other kind of values should be put in .context)
`reporter`
~~`toner`~~ (better to remove this property if there is no one use it)

>since we are using the same object that the user is passing we have a possible vulnerable scenario if the original object (from user) contains a special property that some extension is using, i think that the possibility that something like that could happen decreases the predictability of the system.

also to mitigate those kind of problems i would like that we pick only well known properties (like template, data, options) from the object passed to `reporter.render()` and then deep clone the values in there, having something like that will prevent the user to "hack" the render pipeline by passing something like `{ template: {}, context: {/*fake values to make extensions work in different ways*/} }`, of course to achieve this we would also need to revisit what actually extensions are  storing in `request.template` and if possible move those values to `request.context`.

## what we have currently in `response` object:

the `response` object is in much better state that the `request` object, it is actually the same plain object in both http and module contexts so i just have some comments in this case:

**the current structure of `response`:**

`headers` -> values set by extensions that will be picked by `jsreport-express` to set some headers using `expressResponse.setHeader`
`content` -> the actual result of render pipeline
`stream` -> the result of render pipeline as a nodejs stream
`result` -> same value as `stream`
`logs` -> set when using `jsreport-debug`

## my proposed structure for `response` object:

**`meta`** -> any value that an extension or recipe would like to provide to the user should be put here, basically same as what we have in `headers` now but with the difference that the name `meta` is universal in any context, we can even from jsreport-core put here some standard values like "filename", and extensions can use that value to set headers or other things, note that my intention is that `meta` is just information about the render pipeline that can be used by the user (like `filename`, `extension` etc)
`headers` -> same as what we have now, these values should be set when extensions detect that are running in http context, with the help of `request.context.isHttp` or something like that,  then jsreport-express would pick the values the same way as we have know, the difference is that i would like that `headers` this time would only be visible by jsreport and extensions, the final response for the user should not include this property, so they won't see a `.headers` property when they are just rendering from command line, etc
`content` -> same as what we have now
`stream` -> same as what we have now
`result` -> same as what we have now
`logs` -> same as what we have now

let me know your opinion about this 😄

**Comment by pofider** [comment]
**options property**
There are three main properties on the request body - template, data and options. The template represents the report meta definition and its inner properties should match the schema of template entity. The data are dynamic values passed to the templating engine. Finally the options are configuration values for the particular rendering request. These values are not being persisted inside template and are also separated from the dynamic values passed in data. I didn't want the API consumer to merge data and options together so I created this new property. The example usage of options property is `preview:true` which identifies the request from the studio or `reports: { save: true }` which instructs reporting extension to store the output stream into the blob storage.

**listeners request parameter**
The listeners mainly need the user invoking the request which cannot be found on the query parameter. There are probably also other cases when it makes sense to propagate the essential request down the code stream through listeners.

**difference between the API and background requests**
It is not true that the extensions expect the express object. The extension should always check if it is the express object, usually through checking the `req.url` which is not nice.

## proposed request structure
I understand your main point is to extract express request object and also other stuff to the dedicated `context` property. I would go even further and get rid of the express request instance completely. It would make the API and pipeline cleaner and avoid dependency on particular technology.

It seems to me that we use the express instance only to determine the server url
https://github.com/jsreport/jsreport-assets/blob/master/lib/assets.js#L119
https://github.com/jsreport/jsreport-browser-client/blob/master/lib/browser.js#L23

What if we would calculate this value inside the jsreport-express extension and pass it as a simple string instead of the big unpredictable object.

I would like that the request object is in the end the plain object without functions which we can easily serialize or clone as we need. This is the basic behavior in jsreport because it often sends the request across processes.

This would not only mean eliminating the express instance but also the reporter, toner and logger. The first doesn't need to be there at all. The last could be tricky, but maybe it would make more sense to write logs like this instead of calling functions on request.
```js
reporter.logger.info('foo', request)
```

I keep this proposal open for discussion. Maybe it makes sense to keep the request object as mixture of functions and properties and only serialize clone known properties.

What we need to keep in mind is that the `data` property can have even 80MB size and deep clone is likely a performance killer in this case.

The next thing is that scripts extensions heavily uses `req.options.isChildRequest`.

## my proposed structure for response object:
Shouldn't the `logs` be part of the meta in this case?
Maybe we should merge the meta and headers somehow together so the extension doesn't need to set it twice.
It would make sense to analyze we have three properties for the same purpose `content, stream, result`.

It will take a while to finalize this. :)

**Comment by bjrmatos** [comment]
> I would go even further and get rid of the express request instance completely. It would make the API and pipeline cleaner and avoid dependency on particular technology.



> What if we would calculate this value inside the jsreport-express extension and pass it as a simple string instead of the big unpredictable object.



> I would like that the request object is in the end the plain object without functions which we can easily serialize or clone as we need. This is the basic behavior in jsreport because it often sends the request across processes.

> Maybe it makes sense to keep the request object as mixture of functions and properties and only serialize clone known properties.

i really like this direction, the best would be a plain object, easy to serialize and deserialize, but if we need to put some functions on there i think we are fine with that too

> What we need to keep in mind is that the data property can have even 80MB size and deep clone is likely a performance killer in this case.

yes, i thought about that too, my intention was only to be able to not mutate the object passed from the user, which makes the whole render pipeline not idempotent from the user perspective, which i think is not nice. so it seems like we can do a shallow clone with object.assign but we will need to make sure to not update the `template, data, options` properties in extensions, we would need use something like the `context` to assign/read custom values set by extensions





> Shouldn't the logs be part of the meta in this case?
> Maybe we should merge the meta and headers somehow together so the extension doesn't need to set it twice.

yes, you are right, definitely `logs` should be part of meta too.

> It would make sense to analyze we have three properties for the same purpose content, stream, result.

maybe it makes sense to use streams only, to better handle memory, i think because we have `content` we are allocating pdf files in memory which is not nice, maybe it will be tricky to try to standardize everything as a stream but we can try. 

we can just provide some helper to concat all the content of the stream (much like the helper present in jsreport node.js client) by this would need to be called from user code.

**Comment by pofider** [comment]
Streams would be nice, yes. The reason we don't work with them is mainly because the templating engines don't work with streams. So we need to keep anyway whole output in the html. Then we need string to replace assets. Finally we need to go back to string again because of the child templates. Let me know if you find a way how to streamify this whole process. 

Shallow copy, sure, make sense. Maybe we could do deep copy on template and options, just omit the data deep cloning, but it would not be consistent.

So it is clear we would like to abstract our the express object completely and also would like to keep the request object plain if it will be possible. At the first step we can have still express object and new abstraction and later just remove the deprecated usage.

**Comment by rodriguise** [comment]
I would like to the http query vars in the request object, so the links generated by studio can be more flexible.

**Comment by pofider** [comment]
@rodriguise You mean that you can add query param to the template link `/templates/SJ42AvScg?foo=xxxx` and reach it inside script or templating engine, right?

**Comment by rodriguise** [comment]
Yes. I couldn't figure out if this was possible as the req object didn't seem to expose anything. But, this would greatly simplify our ability to expose reporting to 3rd parties.

**Comment by pofider** [comment]
@rodriguise The current solution how you can reach the query params can be found here https://github.com/jsreport/jsreport/issues/218

**Comment by pofider** [comment]
Main for properties on the request object. We want the object to be plain - no functions.
```
template
options
data
context
```

The context will have dynamic structure, core or extensions can add there something. Everything should be nicely cloneable so we can send it to the scripts external process.

```
isChildRequest
id
user
http: { serverUrl, headers, query, url ... }
reportCounter
...
```

The `context.http` property adds the express extension. It will contain some properties from the original express request instance, but it won't be that instance.

We will get of the `request.reporter` or `request.toner`. These are deprecated for long time.

The `request.logger` will be tricky, but we could possibly do it. The syntax would make anyway more sense to me:
```
reporter.logger.info('Hello world', request)
```

I have not done it originally because it requires more complex implementation. However now it seems right to do it. 

jsreport.core should to clone on the incoming object to avoid modifying the original properties.

**Comment by pofider** [comment]
So we have a gold on this new request schema. @bjrmatos  will just try to prototype that the logging is doable. We could easily be back compatible here and change stuff step by step. The only requirement to not break the user's template is to keep the `options.isChildTemplate` which is used in user's scripts.

**Comment by bjrmatos** [comment]
@pofider 👌 added to the list

**Comment by pofider** [comment]
Response object would have these properties.

```
content
meta
```

meta would be

```
logs
numberOfPages
contentType
fileExtension
```

The express extension would add the `response.meta.headers`. Which also means it won't be there in cli or node.js like response. In http request, the extensions could use this to add additional response headers.

```
if (response.headers) {
	response.headers['Number-Of-Pages'] = numberOfPages
}
```

The express extension then takes this at the end of the request and copy headers into the real response headers.

I would like to bother extensions as less as possible. So for example `meta.fileExtension` or `meta.contentType` would be automatically used by the express to convert into headers.

Regarding the duality of `response.stream` and `response.content`. This is again not very pretty.  We need a lot strings or buffers. Streams are just very inconvenient to us. We already do many stream->string conversions when rendering phantom pdf headers for example. Even when we get back the pdf, we send the content as buffer to the custom script, so user can send it through email for example. Do we need this stream form actually? Wouldn't the buffer content be enough?

**Comment by bjrmatos** [comment]
looks good to me!




> Regarding the duality of response.stream and response.content. This is again not very pretty. We need a lot strings or buffers. Streams are just very inconvenient to us. We already do many stream->string conversions when rendering phantom pdf headers for example. Even when we get back the pdf, we send the content as buffer to the custom script, so user can send it through email for example. Do we need this stream form actually? Wouldn't the buffer content be enough?

yes, the buffer content should be enough.. i was just worried about the fact that maybe we can do it better, right now if you render a big report all of its content (a big buffer) will be in server memory which can be a killer operation when rendering something really big and that could make node.js die.. but handling with streams at least the result output will make possible to not die when doing something big because the user can pipe the result of the stream directly to the filesystem or http response and nodejs will handle everything more efficiently (processing by chunks), anyway the bigger thing present in the render pipeline should be the actual output so maybe it makes sense to handle that part (sending the output to user) with streams and keep the other parts (compiling templates, etc) in its current form.

**Comment by pofider** [comment]
The thing is that the output of templating engine is string which is normally way way bigger than the compressed xlsx or pdf. So the memory consumption of `response.content` is irrelevant?

Or I misunderstood it and you want to give the `response.stream` only to the consumer?

**Comment by bjrmatos** [comment]
> Or I misunderstood it and you want to give the response.stream only to the consumer?

yes, only to the consumer.

but if the output of template engine is more bigger than the actual output then we are still going to have that consumption no matter what we do, which makes me think that in fact the memory consumption of `res.content` will be irrelevant at that point just like you said, because the process anyway will need to have some of the resources with bigger size than the output in memory

**Comment by pofider** [comment]
yes, that was my point. So you can later start working on it. You will probably get stuck on many questions in time. However it is ready at list at conceptional level. Thank you very much for the initial proposal, analysis and final discussion, great job!

**Comment by bjrmatos** [comment]
> So we have a gold on this new request schema. @bjrmatos will just try to prototype that the logging is doable.

just to confirm that logging is 👌 with the new shape of request object, it is working registering a logger rewriter [here](https://github.com/jsreport/jsreport-core/blob/master/lib/reporter.js#L316):

```js
// registering rewriter for saving logs per request in .context
  self.logger.rewriters.push(function (level, msg, meta) {
    if (meta.context && meta.context.id) {
      meta.context.logs = meta.context.logs || []

      meta.context.logs.push({
        level: level,
        message: msg,
        timestamp: meta.timestamp || new Date()
      })

      // excluding non relevant properties for the log
      return _.extend({
        requestId: meta.context.id
      }, _.omit(meta, ['template', 'options', 'data', 'context']))
    }

    return meta
  })
```

also i would like that we define the request object with something like this:

```js
request = Object.create({}, {
    __isJsreportRequest__: {
      value: true,
      writable: false,
      configurable: false,
      enumerable: false
    }
  })
```

the intent of `__isJsreportRequest__` property is to be able to make a more strict check in the rewriter and to avoid any possible collision with other meta objects: 

```js
if (meta.__isJsreportRequest__ === true && meta.context && meta.context.id) {
```

we don't have any downside with that property and it is practically invisible in logs

**Comment by pofider** [comment]
This looks very nice. Great job!

**Comment by pofider** [comment]
Done in v2 beta. 
https://jsreport.net/blog/jsreport-v2-beta
https://github.com/jsreport/jsreport/releases/tag/2.0.0-beta
