### ISSUE TITLE
OAuth2 support

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#274]
Analyze implementation of OAuth2  standard.

**Comment by jshb** [comment]
I'm using [IdentityServer3](https://github.com/IdentityServer/IdentityServer3) to provide a single sign-on via token-based authentication for various web apps.

I'm looking to also implement this for jsreport at some point, which currently only supports basic authentication.

I've implemented this before in node applications using [oidc-passport](https://github.com/davidyum/passport-openidconnect).

**Comment by pofider** [comment]
@jshb Thank you for your notes, I see single sign-on can be very useful. We will definitely look on this in the next days.

**Comment by bjrmatos** [comment]
some analysis about what needs to be done:

First as a matter of clarification, i will add a definition for each actor and concept that plays a role when talking about OAuth2

- `Resource Owner or user`: The user or entity that owns the data, in other words, is the person who is giving access to some portion of their account/data. **in the case of `jsreport`, a jsreport user with an account.**
 
- `Resource Server`: The server hosting the protected data of a user (for example Google hosting your profile and personal information). **in the case of `jsreport`, a standard jsreport server.**

- `Client (usually a third-party Application)`: An application requesting access to a `resource server` (it can be a website, a javascript application or a mobile application, etc), which means an application that wants to get or do something with the data of the `resource server`, this data could be associated with an `user (resource owner)` or not. **in the case of `jsreport`, any application that wants to connect to jsreport and render some template or do other things (like listing, creating, deleting templates through API, advanced use cases etc).**

- `Authorization Server`: The server issuing access tokens to the `client`, this token will be used for the `client` to do requests the `resource server`. the server can be the same as the `authorization server` (same physical server and same application), and it is often the case. **in the case of `jsreport`, a standard jsreport server with authentication extension enabled (the logic of the authorization server will probably need to live in `jsreport-authentication` extension)**

- `Confidential implementation`: A OAuth2 flow where the `client` doesn't leak its confidential information (`client secret`) to the user (or its devices), in other words a `client` that can **safely** protect its `client secret` and can keep that information confidential. (Ex: `clients` that only send its `client secret` in server to server communication, `web servers`)

- `Public implementation`: A OAuth2 flow where the `client` can leak its confidential information (`client secret`) to the user (or its devices), in other words a `client` that **can not protect** its `client secret`. (Ex: `clients` that because its nature can't keep its `client secret` secure, `javascript only apps, mobile apps, desktop apps`)

In simple words, OAuth2 is just a protocol that determines if a `client` can be granted access to some resource, to do this the protocol supports grants or flows designed to work depending on the type of the `client`. the protocol works by issuing tokens to `clients`, these tokens represent a grant with limited access to some resource that lives in the `resource server`.

OAuth2 has four major grants/flows and we should decide if we would like to implement all flows or only the ones that makes more sense right now for `jsreport`:

- Client credentials flow
- Resource Owner Password flow (a.k.a Password flow)
- Implicit Flow (a.k.a Client Side flow)
- Authorization Code flow

i'm going to describe briefly each flow and add my comments about if right now the flow makes sense for us or not, but before the explanation please have in mind that all flows/grants works by the concept that `clients` needs to be registered in some way in the `resource server`, the `resource server` gives to the `clients` the famous values of `client id` and `client secret` in order to identify each `client` in the `resource server`. **for `jsreport` this means that we will probably need to add a new page for managing `external apps (clients)`, in which we will allow registering `external apps` and then assign a `client id` and `client secret` to each one**, an option to avoid creating this maintenance page would be to treat current user names and user passwords as client's id and secrets (user name = client id, user password = client secret) and essentially each jsreport user would be a `client`, but i'm against this because **is not future proof**, treating a user the same way as a `client` would limit the ways that an external application can interact with jsreport, in fact the separation is good because a jsreport administrator will have more control about what resources an external app can access which can't be done easily using just user accounts, so the new maintenance page will be well justified.

## Clients credentials flow

***Supports a `Confidential implementation`***

- The `client` (application) passes the `client id` and `client secret` to the `authorization server`.
- The `authorization server` verifies the `client id` and `client secret` and passes an `access token` to the `client`.
- The `client` uses the `access token` to get or use some resource in the `resource server`.
- The `resource server` passes the required data to the `client`.

Example use case: 

example.com stores its files of any kind on Amazon S3, the website must go through the Amazon S3 API to retrieve or modify files and must authenticate with the `authorization server`.
Once authenticated, example.com obtains an access token that can now be used for querying the `resource server` (Amazon S3).

Resource Owner: example.com
Resource Server: Amazon S3
Client: example.com
Authorization Server: Amazon authorization server

As you can see there is no real `user` involved in this flow (the `resource owner` is a machine/server), and that is the reason i think this is the perfect flow for jsreport and it will be the most used. i think that jsreport is mostly used as an internal server, which is used in all your applications that needs some kind of reporting, this means that basically jsreport is treated like a reporting worker who you can send some tasks from your applications, the communication is only between app <-> jsreport, there is no user involved (the user is probably part of the application itself but jsreport is agnostic about that)

**opinion: we should implement this flow**

## Resource Owner Password flow (a.k.a Password flow)

***Supports a `Confidential implementation`***
***Supports a `Public implementation`***

- The `user` provides a user name and password to the `client` (application).
- The`client` provides the user name and password along with its `client id` and `client secret` to the `authorization server`.
- `authorization server` verifies the user name, password and `client` credentials and sends an `access token` to the `client`.
- The `client` uses the `access token` to get or use some resource in the `resource server`.
- The `resource server` passes the required data to the `client`.

Example use case:

Example company, makes an API (api.example.com) for thrid-party applications, this company thinks it would be convenient to use its own API to avoid reinventing the wheel, so Example company needs an `access token` to call the methods of its own API, for this, Example company asks you to enter your login credentials via a standard HTML form as you normally would, the server-side application (website example.com) will exchange your credentials against an `access token` from the `authorization server`, its own `client` (example.com) can now use the access token to query its own `resource server` (api.example.com).

Resource Owner: You having an account on example.com website of the Example company
Resource Server: Example company exposing its API at api.example.com
Client: example.com website from Example company
Authorization Server: an Example compny server

This flow is a.k.a the "trust flow", because it should only be used with **trusted first party clients**, i can imagine an scenario where someone wants to use OAuth2 authentication using an standard jsreport account (user and password) (maybe jsreport is part of a node.js app and the administrator don't want to register the same application as an "external app", basically they don't see the need to a `client id` or `client secret`).

**opinion: we should implement this flow**

## Implicit Flow (a.k.a Client Side flow)

***Supports a `Public implementation`***

- The`client` passes to `authorization server` a `client id` in conjunction with an attempted sign-on.
- `authorization server` requests to `user` to enter its login credentials through an authorization form on a gateway server (usually hosted in the `authorization server` itself)
- The `user` enters their information and sends the login credentials to `authorization server`.
- `authorization server` passes an `access token` to the `user`.
- The `user` provides the `access token` to the `client`.
- The `client` uses the `access token` to get or use some resource in the `resource server`.
- The `resource server` passes the required data to the `client`.

Example use case:

The `client` (a React.js application) wants to obtain information about your Facebook profile, `user` is redirected by the browser to the `authorization server` (Facebook), if `user` authorize access, the `authorization server` redirects the `user` to the `client` with the `access token` in the URI fragment. Example of callback: http://example.com/oauthcallback#access_token=MzJmNDc3M2VjMmQzN,
this `access token` can now be retrieved and used by the `client` (React.js application) to query the `resource server` (Facebook).

Resource Owner: You having an account on facebook.com 
Resource Server: a Facebook server
Client: a website using React.js for example
Authorization Server: a Facebook server

This flow is used in single page apps (React, Angular, etc apps), mobile and desktop apps, and requires the `user` to authorize the access of the `client` to its data with an authorization form, currently for jsreport i don't see a good use case for this flow, i don't see an use case where a `client` redirects the `user` to an authorization form (provided by jsreport), this flow makes more sense for products with more useful and actionable data, but i think this is not the case for jsreport because the user will probably only need to render reports without the need to get information about jsreport resources.. maybe the use case exists but i'm sure it is something really advanced

**opinion: we should not implement this flow for now**

## Authorization Code flow

***Supports a `Confidential implementation`***
***Supports a `Public implementation`***

- The `client` passes to `authorization server` a `client id` in conjunction with an attempted sign-on.
- `authorization server` requests the `user` to enter its login credentials through an authorization form on a gateway server (usually hosted in the `authorization server` itself).
- The `user` enters their information and sends the login credentials to `authorization server`.
- `authorization server` passes an `authorization code` to the `user`.
- The `user` provides the `authorization code` to the `client`.
- The `client` sends the `authorization code` and the `client secret` to `authorization server`.
- `authorization server` verifies the `authorization code` and `client secret` and passes an `access token` to the`client`.
- The `client` uses the `access token` to get or use some resource in the `resource server`.
- The `resource server` passes the required data to the `client`.

Example use case:

example.com wants to obtain information about your Google profile, you are redirected by the client (example.com) to the authorization server (Google), if you authorize access, the authorization server sends an authorization code to the client (example.com) in the callback response, then, this code is exchanged against an access token between the client and the authorization server, the website is now able to use this access token to query the resource server (Google again) and retrieve your profile data, the `user` will never see the access token, it will be stored by the website (in session for example).

Resource Owner: You having an account on Google
Resource Server: a Google server
Client: example.com
Authorization Server: a Google server

this flow is mostly the same as the `Implicit Flow` (with the difference that it supports server-side based `clients` too and with an additional step that requires the exchange of an `authorization code` before getting the `access token`), it requires the `user` to authorize the access of the `client` to its data with an authorization form, and again i don't see a good use case for this flow

**opinion: we should not implement this flow for now**

### Next steps

- decide if we should add an option in [nodejs-client](https://github.com/jsreport/nodejs-client) to support connecting to jsreport using OAuth2
- investigate what we need to do provide support for single sign-on/identity server providers. (maybe @jshb has some comments about this)
- review express request responses in our codebase to see if we need to make them more json friendly
- review [jsreport authentication](https://github.com/jsreport/jsreport-authentication) and [jsreport authorization](https://github.com/jsreport/jsreport-authorization) extensions to see if something needs to be adapted.
- make sure that we promote the usage of OAuth2 only on jsreport servers with https for security reason (OAuth2 of course can work in plain http too but we should promote https as the best practice)  

some good resources about OAuth2 (with good explanation and diagrams):

https://strongloop.com/strongblog/securing-api-oauth/
https://alexbilbie.com/guide-to-oauth-2-grants/
http://www.bubblecode.net/en/2016/01/22/understanding-oauth2/

i hope that everything is clear 😃 i've left technical details out intentionally, so we can focus on discussion about what flows we are going to implement.

**Comment by bjrmatos** [comment]
to provide support for exposing `jreport` as part of a suite of products which are delegating authentication to an Authorization/Identity Provider Server (Single Sign on support) we need to do the following:

- we need to protect our resources endpoints additionally with tokens (probably using a [token strategy](https://github.com/jaredhanson/passport-http-bearer))
- in token validation logic we will send a request to a configured external endpoint (an endpoint in a Authorization/Identity Provider Server), this endpoint should return if a token is valid or not, if the request to the endpoint succeds, the token is valid and we will continue with the requested operation, if the request fails we will assume that the token is invalid and we will respond with an error
- we would probably need to add an option to [nodejs client](https://github.com/jsreport/nodejs-client) for sending requests with a token.

***Note: delegating jsreport studio login to an external Authorization Server is outside of the scope of this initial support for Single Sign On, we are only providing Single Sign On access to jsreport objects via the http API***


this use case (Single Sign On support) is probably what we want to start to support first, since implementing OAuth2 as part of jsreport doesn't give us any benefit right now, because the current way to access (basic auth) jsreport resources (like rendering reports) is the less complex and what we think its fits all the needs for our users right now.

@jshb our planned Single Sign On support is everything you need? do you see something missing here? please feel free to post your opinion if you see something misleading.

if someone has an opinion or an interesting use case for OAuth2 authentication in jsreport please share with us your thoughts.

**Comment by jshb** [comment]
@bjrmatos that suits me, in my use case the studio will be disabled and all interaction will be through the API.

thanks for all your research on this 👍

**Comment by pofider** [comment]
@jshb We already started development of this. I think there will be prototype or beta version ready in couple of days. It would be great if you helps us afterwards and try to integrate it to your environment. We would really appreciate that.

**Comment by bjrmatos** [comment]
just FYI, the preview and a running sample for our Single Sign On support (using IdentityServer4 as the authorization server) can be found in -> https://github.com/bjrmatos/jsreport-with-authorization-server-sample

feedback welcome!

**Comment by bjrmatos** [comment]
@jshb if you are able to take look at the sample and give us your feedback it will be very appreciated 😄

**Comment by bjrmatos** [comment]
our single sign on support has landed in `1.7.0`, please try it out and give us some feedback 😄
