### ISSUE TITLE
Specifying json file in in API request

### ISSUE THREAD

**Issue by j-sutton** [jsreport/jsreport#282]
With the cli you can specify a template and .json file and bind them together without having to pass json through the request. Is it possible to do the same thing in the request? Where I can generate my json file, send it to a location and then have the request tell it to bind it and the template?

**Comment by bjrmatos** [comment]
> With the cli you can specify a template and .json file and bind them together without having to pass json through the request.

can you clarify me this part a little bit more? maybe show me an example of this to better understand what you want to bring to the API request, just note that passing files in the cli is something that we support to better work in that context.. but passing file paths to the API request is probably something we won't want to support because it will bring too much ambiguity and not worth the effort when you can just read the file and pass the real content to the request.



> Where I can generate my json file, send it to a location and then have the request tell it to bind it and the template?

note that when you use the studio editor, you can bind objects (data, scripts, helpers) to a template and when you want to use that template you can just pass this object to the API request:

```js
{
  template: {
    shortid: '<put the shortid of your template here>'
  }
}
```

jsreport will recognize the template and previous binded objects and fill the rest of options automatically

**Comment by j-sutton** [comment]
I think I'm going to go with the CLI approach, thank you for taking the time to explain it.
