### ISSUE TITLE
mac OS Sierra Start jsreport at SO startup with PM2 not working

### ISSUE THREAD

**Issue by hanselacacia** [jsreport/jsreport#286]
Hi Jan. I installed node from scratch, I install and init jsreport correctly.

I install pm2 with sudo npm install pm2 -g
Start jsreport with sudo pm2 start npm -- start --production: all ok. jsreport running.

sudo pm2 startup --> ok
sudo pm2 save --> ok

But, I restart/shutdown the server and jsreport is not running. :(

What I doing wrong!

Env: macOS Sierra 10.12 / node v6.10.0 / jsreport 1.6

**Comment by bjrmatos** [comment]
hi! after you run `pm2 startup`, you need to run an additional command in order to configure an app to startup on server restart. pay close attention to the log of pm2:

<img width="939" alt="captura de pantalla 2017-04-20 a las 5 27 28 p m" src="https://cloud.githubusercontent.com/assets/4262050/25255117/be527888-25ee-11e7-8dba-9e1d7dc9d95e.png">


also just note that as described in [docs](https://jsreport.net/learn/phantom-pdf#macos-sierra) the default phantomjs version (1.9.0) that comes with jsreport [does not work with macOS Sierra](https://github.com/ariya/phantomjs/issues/14558), you need to use phantomjs 2 (see the [docs](https://jsreport.net/learn/phantom-pdf#phantomjs2) for upgrade instructions).

i'm going to close the issue since it seems that this is a phantomjs + macOS sierra issue or a misunderstanding of `pm2` usage.
