### ISSUE TITLE
on installing jsreport as service

### ISSUE THREAD

**Issue by zeshanhassan** [jsreport/jsreport#294]
I am installing the jsreport server as a service on windows 10 pro version 1703.
it was working fine before updating the windows.
on the command promnt i see this error 

![2017-05-24 11_39_15-c__windows_system32_cmd exe](https://cloud.githubusercontent.com/assets/3735174/26390127/a4349d8a-4076-11e7-8aa2-89d70d2dae03.png)

and if i look into windows event log its showing error 

![2017-05-24 11_39_51-event viewer](https://cloud.githubusercontent.com/assets/3735174/26390195/f407df8e-4076-11e7-97c3-74c8e0bf5bb4.png)

any help I am trying to google the relevant thing i found 
"https://support.symantec.com/en_US/article.TECH240364.html"
can you please help

**Comment by pofider** [comment]
Thank you for reporting this. 
It seems like common problem with creators update and nssm (google "nssm windows creators update")

The current solution which works for me.
1. Download the pre-release of nssm https://nssm.cc/download
2. Extract the release, take the nssm.exe from x64 folder and rename it to nssm64.exe
3. Copy nssm64.exe into `node_modules\winser-with-api\bin\`
4. Run the jsreport win service install (maybe you need to uninstall before)

Hopefully the dependencies we use gets updated soon so we can release hotfix with new nssm.
Otherwise we have to search for different solution.

**Comment by zeshanhassan** [comment]
Thanks its work for my case too :-)

**Comment by pofider** [comment]
Linking submitted issue to the third-party package winser.

https://github.com/jfromaniello/winser/issues/46

**Comment by pofider** [comment]
There seems to be no response from the `winser` maintainers. We will use [fork](https://www.npmjs.com/package/@kanreisa/winser) and hotfix jsreport to include the nssm with the needed fix for win10.

**Comment by pofider** [comment]
@bjrmatos Please take [these binaries](https://github.com/kanreisa/winser/tree/master/bin) and put them to [your fork](https://github.com/bjrmatos/winser). Release it and reference it in the `jsreport-cli`

**Comment by micke911** [comment]
Good work!
Is there a planned release with this fix?

**Comment by pofider** [comment]
@micke911  Today....

**Comment by pofider** [comment]
@micke911 We had a delay because of some bugs found in the final testing, the release will be done tomorrow

**Comment by pofider** [comment]
Released in 1.8.1
