### ISSUE TITLE
Vulnerabilities in JSReport

### ISSUE THREAD

**Issue by samir-kamble** [jsreport/jsreport#298]
Hello,

Just before getting licence client shown us this link 

https://snyk.io/test/npm/jsreport

And said There are vulnerabilities with this tool. Can you please tell us if we can overcome these anyhow?

Regards,
Samir

**Comment by pofider** [comment]
1. Please follow the best practices and email topics regarding vulnerabilities.
2. In 95% of the cases, jsreport is running as an internal application where attacker doesn't have access anyway, so you don't need to worry if this is your case.
3. All the mentioned vulnerabilities are not in actual jsreport code, but somewhere deep down the dependencies. We do update all dependencies regularly to get the latest security fixes.
4. The mentioned errors are at least in cases I saw false positive. There is for example one mentioned somewhere in dependency `request/qs`. We use `request` only to make internal calls to our worker servers and there is no way that the request would include query string. This means if such a tool finds a possible vulnerability in jsreport, just because it uses a particular dependency, it doesn't mean that the vulnerability is actually there.

In every case, thank you for the question. If you have anything else to discuss regarding vulnerabilities, please use my email.
