### ISSUE TITLE
Reports from React

### ISSUE THREAD

**Issue by batjko** [jsreport/jsreport#301]
Hi there,

I'm looking to evaluate reporting engines and jsReport looks like an awesome option out there.
I have seen that the studio allows us to create reports using HTML-base render engines, incl. Handlebars etc.

Has anyone used this with React?
I'm wondering if there is any information out there how one would go about generating a report from a React-based view (given that in React we don't write HTML directly but just as bits and piece of JSX etc. All very dynamic).

Cheers

**Comment by bjrmatos** [comment]
i always had that idea in my mind but i never shared it to anyone 😆 


> Has anyone used this with React?
> I'm wondering if there is any information out there how one would go about generating a report from a React-based view (given that in React we don't write HTML directly but just as bits and piece of JSX etc. All very dynamic).

no, at this time i don't think anyone has experimenting with using React as an engine, but it is definetly possible, you just need to create an [extension](https://jsreport.net/learn/custom-engine) that uses react instead of a template engine (like handlebars) to generate the final html content, you have two good examples of extensions that implement new engines: 

https://github.com/jsreport/jsreport-handlebars 
https://github.com/bjrmatos/jsreport-jade

however i don't know if it will be useful to use React as an engine, maybe it will make sense just to unify the template language with the scripting (in the end the template with be all javascript).

i'm also interested with playing with React as a new pdf recipe, using this custom [react renderer](https://github.com/diegomura/react-pdf), looks promising

**Comment by batjko** [comment]
I suppose I need to learn about more about how the Javascript API actually works and play around with it. 

Ideally, I am looking to give users a kind of online-designer experience, where they can put together their own report (e.g. "I have some tabluar data here, now I want to add a pie chart and line chart... et voila: a new report, let's click export to PDF and boom there it is.").
But from what I see so far, this is not possible with jsreport, or at least not the designer part, just the export-as-pdf part, correct?

**Comment by bjrmatos** [comment]
> Ideally, I am looking to give users a kind of online-designer experience, where they can put together their own report (e.g. "I have some tabluar data here, now I want to add a pie chart and line chart... et voila: a new report, let's click export to PDF and boom there it is.").

wo wo wo wooo! you will definitely love what we are cooking right now, it will solve exactly what you trying to solve 😉

**Comment by bjrmatos** [comment]
> But from what I see so far, this is not possible with jsreport, or at least not the designer part, just the export-as-pdf part, correct?

yes, not possible currently but it will be!

**Comment by pofider** [comment]
Closing this as there is no action we can take right now.

The react based designer is under heavy development [here](https://github.com/jsreport/jsreport-designer). It is in POC phase, please give us at least few weeks before we give a first preview. We will then ask as many people as possible to give us feedback and discuss the API and the usage.

We love reactjs. In fact we use it for all our UI. However there is no "reactness" useful when rendering static pdf or xlsx. That is why we stick with better DX provided by engines like handlebars. If we ever find or get recommend a good fit for react, we will happily use it.

**Comment by batjko** [comment]
@bjrmatos, @pofider That sounds great. I'll be checking back occasionally then to see how that is going.
Thanks for the update!

**Comment by snsheth55** [comment]
Hello, is React now available as a recipe? If so could you please provide an example of how to use it. Thanks

**Comment by MerzDaniel** [comment]
> Closing this as there is no action we can take right now.
> 
> The react based designer is under heavy development [here](https://github.com/jsreport/jsreport-designer). It is in POC phase, please give us at least few weeks before we give a first preview. We will then ask as many people as possible to give us feedback and discuss the API and the usage.
> 
> We love reactjs. In fact we use it for all our UI. However there is no "reactness" useful when rendering static pdf or xlsx. That is why we stick with better DX provided by engines like handlebars. If we ever find or get recommend a good fit for react, we will happily use it.

I'm also currently looking for an option to render from react components. 

I have to disagree with the point you are making concerning "no reactness is needed":
React is also a rich resource for ready made components and libraries for designing these. Internally we have all our designed components as react components. So in order to create branded reports, best would be of course to render them with these existing React components

As there still doesn't seem to be a react-templating extension, I'm think of creating the report templates from react or continue my search for a good reporting solution

**Comment by pofider** [comment]
You can use react in the chrome scope. You don't need an explicit templating engine implementation for it.
https://playground.jsreport.net/w/anon/X8vd5nDI
Doesn't this approach address your needs?
