### ISSUE TITLE
Render issue when trying from nodejs backend

### ISSUE THREAD

**Issue by SunilRumbaLama** [jsreport/jsreport#302]
Hi, i have a jsreport server running at port 8001. Can i not use the content as following?. It gives me TypeError: Cannot read property '1' of undefined. It works fine when i use html to produce a pdf 
```

`/* Testing template from server side. */
router.get('/', function (req, res, next) {
  var data = {
    template: {
      content: `
      {{xlsxRemove "xl/worksheets/sheet1.xml" "worksheet.sheetData[0].row" 1}}
{{#each people}}
{{#xlsxAdd "xl/worksheets/sheet1.xml" "worksheet.sheetData[0].row"}}
<row>
    <c t="inlineStr" s="{{@root.$removedItem.c.[0].$.s}}"><is><t>{{name}}</t></is></c>
    <c t="inlineStr" s="{{@root.$removedItem.c.[1].$.s}}"><is><t>{{gender}}</t></is></c>
    <c s="{{@root.$removedItem.c.[2].$.s}}"><v>{{age}}</v></c>
</row>
{{/xlsxAdd}}
{{/each}}
{{{xlsxPrint}}}
`,
   engine: 'handlebars',
      recipe: 'xlsx'
    },
    data: {
      "people": [{
        "name": "Alex Rumba",
        "age": 25,
        "gender": "male"
      }, {
        "name": "Roshana Bajracharya",
        "age": 22,
        "gender": "female"
      }]
    },
    options: {
      preview: true
    }
  }

  var options = {
    url: 'http://localhost:8001/api/report',
    method: 'POST',
    json: data
  }
  request(options).pipe(res);
});`
```

**Comment by bjrmatos** [comment]
hi! when you use the `xlsx` recipe you need to also pass the `xlsxTemplate` option:

```js
var data = {
    template: {
      content: `
      {{xlsxRemove "xl/worksheets/sheet1.xml" "worksheet.sheetData[0].row" 1}}
{{#each people}}
{{#xlsxAdd "xl/worksheets/sheet1.xml" "worksheet.sheetData[0].row"}}
<row>
    <c t="inlineStr" s="{{@root.$removedItem.c.[0].$.s}}"><is><t>{{name}}</t></is></c>
    <c t="inlineStr" s="{{@root.$removedItem.c.[1].$.s}}"><is><t>{{gender}}</t></is></c>
    <c s="{{@root.$removedItem.c.[2].$.s}}"><v>{{age}}</v></c>
</row>
{{/xlsxAdd}}
{{/each}}
{{{xlsxPrint}}}
`,
   xlsxTemplate: {
     shortid: '<put here the shortid of your xlsx template>'
   },
   engine: 'handlebars',
      recipe: 'xlsx'
    },
    data: {
      "people": [{
        "name": "Alex Rumba",
        "age": 25,
        "gender": "male"
      }, {
        "name": "Roshana Bajracharya",
        "age": 22,
        "gender": "female"
      }]
    },
    options: {
      preview: true
    }
  }
```

first, a `xlsxTemplate` file must be registered in jsreport (most of the time using the jsreport-studio UI), then you can take the shortid of the xlsx template file looking at this file (assuming that you are using the default configuration of jsreport that saves templates in local `data` folder):

<img width="236" alt="captura de pantalla 2017-06-13 a las 12 05 28 p m" src="https://user-images.githubusercontent.com/4262050/27094765-cc6b3664-5030-11e7-8201-1cb8f1f480b5.png">

the `config.json` file will have a property called `shortid`:

in my computer the content of `config.json` is the following:

```json
{
    "shortid": "BkJt9tnql",
    "_id": "e8IGUsjJpAsX7ajw"
}
```

finally, just take the `shortid` value and pass it to jsreport in template property:

```js
   template: {
     // ..other config here...
     xlsxTemplate: {
       shortid: '<put here the shortid of your xlsx template>'
     }
     // ..other config here...
   },
   // ..other config here...
```

**Comment by SunilRumbaLama** [comment]
Hi there, the whole idea is about not using the template from the UI and using the template from the backend. It works for html however, for xlsx, its not working. Using shortid, we can directly use the xlsxTemplate that we have created in the UI.

**Comment by bjrmatos** [comment]
> Hi there, the whole idea is about not using the template from the UI and using the template from the backend.

yes, but in order to use the `xlsx` recipe you need to have a **registered (with a shortid)** xlsx template file, the file must be registered in jsreport first and currently there is no way to pass that file directly in raw format when rendering something, the file needs to be registered always. 

in normal cases you just need to register all the xlsx templates that you are going to use in the UI (jsreport-studio), then just take all shortid of the xlsx templates and use it from your backend normally, no need to use the UI when rendering something, you just use the UI for the registering of xlsx template files.

but if for some reason you need to send everything from backend (even the xlsxTemplate) then you will need to register the xlsx template programmatically with the jsreport API.

example:

```js
jsreport.documentStore.collection('xlsxTemplates')
        .insert({
            // put here the raw content (base64 string) of the xlsx template file, 
            contentRaw: fs.readFileSync(path.resolve('./template.xlsx')).toString('base64'), // this is just an example assuming that the xlsx template is in your directory, you can also use some data that you have sent from other server
            name: 'nameofmyxlsxtemplate' // name of the new xlsx template file
        })).then(function (doc) {
           console.log(doc.shortid); // you should have the generated shortid here, which you can use to pass it to jsreport
        })
```

later if you need to clean up the registered xlsx template

```js
jsreport.documentStore.collection('xlsxTemplates')
            .remove({name: 'nameofmyxlsxtemplate'})).then(function () {
   // the file is deleted here
})
```

**Comment by pofider** [comment]
I think that it would be useful to provide ability to pass the xlsx template content directly inside the request without persisting the template inside the jsreport store in advance. I've submitted bug for it here https://github.com/jsreport/jsreport-xlsx/issues/26

**Comment by SunilRumbaLama** [comment]
@bjrmatos how do i access the documentStore. Until the bug is resolved i tried the following, but it says cannot read property collection of undefined.
`var express = require('express');
var router = express.Router();
var request = require('request');
var fs = require('fs');
var jsreport = require('jsreport-core')();

/* GET users listing. */
router.get('/', function (req, res, next) {
  jsreport.init().then(function () {
    require('jsreport').documentStore.collection('xlsxTemplates')
      .insert({
        // put here the raw content (base64 string) of the xlsx template file, 
        contentRaw: fs.readFileSync(path.resolve('./template.xlsx')).toString('base64'), // this is just an example assuming that the xlsx template is in your directory, you can also use some data that you have sent from other server
        name: 'hello' // name of the new xlsx template file
      }).then(function (doc) {
        console.log(doc.shortid);

        return jsreport.render({
          template: {
            content: fs.readFileSync(path.resolve('./template.xlsx')).toString('base64'),
            xlsxTemplate: {
              shortid: doc.shortid
            },
            engine: 'handlebars',
            recipe: 'xlsx'
          },
          data: {
            "people": [{
              "name": "Alex Rumba",
              "age": 25,
              "gender": "male"
            }, {
              "name": "Roshana Bajracharya",
              "age": 22,
              "gender": "female"
            }]
          },
          options: {
            preview: true
          }
        }).then(function (resp) {
          //prints pdf with headline Hello world 
          resp.stream.pipe(res);
        });

      }).catch(function (e) {
        console.log(e)
      })

  });
});

module.exports = router;`

**Comment by pofider** [comment]
Use already created instance of jsreport.
```js
var jsreport = require('jsreport-core')();
jsreport.documentStore.collection....
```

**Comment by SunilRumbaLama** [comment]
@pofider  yes, that helped however now it throws unable to parse xlsx template JSON string (maybe you are missing {{{xlsxPrint}}}). Below is the xlsx i am using.

```
 {{xlsxRemove "xl/worksheets/sheet1.xml" "worksheet.sheetData[0].row" 1}}
{{#each people}}
{{#xlsxAdd "xl/worksheets/sheet1.xml" "worksheet.sheetData[0].row"}}
<row>
    <c t="inlineStr" s="{{@root.$removedItem.c.[0].$.s}}"><is><t>{{name}}</t></is></c>
    <c t="inlineStr" s="{{@root.$removedItem.c.[1].$.s}}"><is><t>{{gender}}</t></is></c>
    <c s="{{@root.$removedItem.c.[2].$.s}}"><v>{{age}}</v></c>
</row>
{{/xlsxAdd}}
{{/each}}
{{{xlsxPrint}}}
```

**Comment by bjrmatos** [comment]
@SunilRumbaLama according to your last code you are not sending correct content in  `template.content`, you have this: 

```js
template: {
  //....
  content: fs.readFileSync(path.resolve('./template.xlsx')).toString('base64'),
  //...
}
```

if you have more issues it will be much faster if you upload the code in a repository, so we can have a better idea of the full picture and help with some corrections.

**Comment by SunilRumbaLama** [comment]
@bjrmatos here is the link to repo: [https://github.com/SunilRumbaLama/jsRenderIssueXlsx](url). Inserting template did not do the trick. I tried using 

```
template: {
  //....
  content: fs.readFileSync(path.resolve('./template.xlsx')).toString(),
  //...
}
```
It says cannot read worksheet of undefined.

**Comment by bjrmatos** [comment]
ok after taking a look i've found the following:

- first you have installed `jsreport` and `jsreport-core` at the same time, even if apparently it would not cause any problems if you only use one and not the other (like in your case you are using `jsreport-core` in your app but `jsreport` was not used at all), the presence of one will have an effect in the other, for example, if you only use `jsreport-core` and have installed both `jsreport` and `jsreport-core`, `jsreport-core` by default will load all extensions detected in your `node_modules`, when using npm >=3 all installed dependencies are created at the root of `node_modules`, so jsreport-core will auto-discover the extensions of `jsreport` too. i'm only describing this because this behaviour was actually hiding that `jsreport-xlsx` can not be used without having `jsreport-data` and `jsreport-templates` installed cc @pofider. we will try to eliminate this dependency, since it should work without those extensions installed.

- you were [not using valid content in  `template.content` option](https://github.com/SunilRumbaLama/jsRenderIssueXlsx/blob/master/routes/books.js#L25), solved by using valid content:

```js
content: `
              {{xlsxRemove "xl/worksheets/sheet1.xml" "worksheet.sheetData[0].row" 1}}
              {{#each people}}
              {{#xlsxAdd "xl/worksheets/sheet1.xml" "worksheet.sheetData[0].row"}}
              <row>
                <c t="inlineStr" s="{{@root.$removedItem.c.[0].$.s}}"><is><t>{{name}}</t></is></c>
                <c t="inlineStr" s="{{@root.$removedItem.c.[1].$.s}}"><is><t>{{gender}}</t></is></c>
                <c s="{{@root.$removedItem.c.[2].$.s}}"><v>{{age}}</v></c>
              </row>
              {{/xlsxAdd}}
              {{/each}}

              {{{xlsxPrint}}}
            `
```

- your `template.xlsx` file was corrupted for some reason, corrupted files will not be read correctly and that is the reason for why you saw errors like `cannot read worksheet of undefined`, i tried to open your `template.xlsx` file with office and the file was corrupted also there.

i've sent you a [PR to your repository](https://github.com/SunilRumbaLama/jsRenderIssueXlsx/pull/1) with these problems solved.

**Comment by SunilRumbaLama** [comment]
@bjrmatos You are not getting the jest of what i want. Since, you said that we need to first insert the template on the jsreport. What i do first is save the template in  a file for future reference, now that same template should act as the content, why would i write the template on the content section when i have saved it on the file. Like i read and used it in the raw section, i am facing problem when i try to use it in the content section :/
