### ISSUE TITLE
Add npm-shrinkwrap.json to get consistent installs

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#303]
Just call `npm shrinkwrap` before npm publish with `npm@5` during the next release.

**Comment by pofider** [comment]
@bjrmatos  Is this is really so useful it makes sense to bother with it? The same with `package-lock.json`. Packages I tried like `koa`, `express`, `winston` don't include them. I'm already getting board with the lock file. :)

**Comment by bjrmatos** [comment]
> Is this is really so useful it makes sense to bother with it? The same with package-lock.json. Packages I tried like koa, express, winston don't include them

i think jsreport it is more an app and less a library like `express` so i think that it matters a lot for our case to have the reliability that at any time you will get the exact dependencies for the specific jsreport version that you are trying to install, for a normal app i would do the same and since i saw jsreport as an app that you install and just configure i think it makes sense to lock with `npm-shrinkwrap.json` here too.

**Comment by bjrmatos** [comment]
this matter even more because we distribute jsreport also as an executable

**Comment by pofider** [comment]
Ok. Marking for v2. Thanks.

**Comment by pofider** [comment]
Closing in favour of more general
https://github.com/jsreport/jsreport/issues/400
