### ISSUE TITLE
passing functions in preRender script

### ISSUE THREAD

**Issue by cesartl** [jsreport/jsreport#319]
I'm trying to programmatically control the content of my reports using js files.

I have a js files in my assets, which I load in a preRender call:

```
{#asset salesReportConfig.js}

function beforeRender(req, res, done) {
    req.data.config = config
    done();
}
```
salesReportConfig.js:
```
const config = {
    value: 'foo',
    f: function(x){
       return x + 1;
    }
...
}
```

The problem is that my config object contains functions. The plain JS object are available as expected in the templates, but the functions are not. I'm guessing the data object is being serialised which is why the functions are not passed properly.

How else could I add js code from asset files? I thought about loading the the file inside the `req.template.helpers` but I can find no documentation helping with that.

**Comment by bjrmatos** [comment]
you have two options to achieve what you want.

- first, using the `in-process` strategy for tasks, take a look at the [config](https://jsreport.net/learn/configuration#script-tasks) for tasks, specifically the `tasks.strategy` config, jsreport by default executes scripts in a node.js sandbox, another node.js process different than the one in which jsreport is running (main process), this is due to security reasons and to prevent third-party code to affect your main process. To pass data to the sandbox we need to serialize the values of `req.data` and as you already found, when someone serializes an object with functions, the functions are practically lost. To prevent this you can set `tasks.strategy` to the `in-process` strategy, which basically means jsreport will not create any sandbox, and it will just run scripts, etc in the same main process of your application, which means that there will be no need to serialize `req.data` and your functions will be preserved. if you control every dependency, helpers, templates of your jsreport installation then using the `in-process` strategy should be ok.

- the last option that you have (without changing the `tasks.strategy`) is to move any function in your object to a separate asset file and then use its content to set the `req.template.helpers` in your scripts.

```js
// salesReportConfig.js asset
var config = {
    value: 'foo'
}
```

```js
// helpers.js asset
function addOne(x){
    return x + 1;
}
```

```js
// your script file
{#asset salesReportConfig.js}

function beforeRender(req, res, done) {
    req.data.config = config
    // the magic thing here is the @encoding=string, see https://jsreport.net/learn/assets#encoding-options for an explanation
    req.template.helpers = "{#asset helpers.js @encoding=string}"
    done();
}
```

and finally you will be able to use the helper in your template normally:

```html
{{config.value}}
{{addOne 1}}
```

**Comment by pofider** [comment]
Closing. Feel free to continue chat here if you need.
