### ISSUE TITLE
image placing on header and footer

### ISSUE THREAD

**Issue by vinithios** [jsreport/jsreport#324]
i am struggling in image placing on both header and footer.can you please explain how to place image in header?

**Comment by vinithios** [comment]
It's not visible when i give actual folder image path, rather it works when the "http image path" is there.Why it happens?

**Comment by pofider** [comment]
Please try to better describe your questions. This is really poor.
What recipe you use, which version of jsreport, what kind of distribution, give an example in playground... I can just assume you are actually asking for....

Normally you upload image as an [asset](https://jsreport.net/learn/assets) and then reference it in header. Just be aware of this phantomjs bug - https://jsreport.net/learn/phantom-pdf#images-in-header-and-footer

**Comment by vinithios** [comment]
> sry for the inconvenient  communication.

can you please say, how to wrap the footer content.I need to make it footer as,
```
date(17-08-17)
place(Chennai) 
```

I attached the server code for footer. 
[file.txt](https://github.com/jsreport/jsreport/files/1231188/file.txt)

**Comment by bjrmatos** [comment]
@vinithios you are using relative paths to reference your images, that does not work by default because some default options, so you have a couple of things to get your desired result:

- you can use the [base options](https://jsreport.net/learn/base) to allow the proper resolution of relative paths in your html (as described in docs you will also need to `allowLocalFilesAccess` in phantom) 

- you can use [assets](https://jsreport.net/learn/assets) to reference your image using something like `<img src='{#asset logo.png @encoding=dataURI}'/>` in your header/footer

- you can host the image in a public server and just use the public url to reference the image in your header/footer

hopefully this will help you to solve your problem. (also don't forget about the [described issue with phantom and images in header/footer](https://jsreport.net/learn/phantom-pdf#images-in-header-and-footer))

**Comment by vinithios** [comment]
Thanks @bjrmatos.
