### ISSUE TITLE
html page rendering with header and footer

### ISSUE THREAD

**Issue by vinithios** [jsreport/jsreport#325]
How to render html page with header and footer which i have referenced in server side?we can use header and footer only inside phantom{} like the below, 

> phantom{
         "header":  "title",
         "footer": "quote"
}
 
But, there is no more relation between phantom and html.
Anyone say how to render html page with header and footer?I attached my code below.
[file.txt](https://github.com/jsreport/jsreport/files/1233340/file.txt)

**Comment by bjrmatos** [comment]
header/footer only makes sense in the context of PDF (like when using the phantom recipe that produces PDF) because those are things that will be repeated  in every paper page, a part of content that can't be controlled in a nice way in html. when using the `html` recipe you are producing just a webpage so technically there is no header/footer in that context, you can make any element in your page behave like a header or footer by using some css. are you doing something special? what will be a header/footer in the context of your page and use case?

**Comment by vinithios** [comment]
> Sorry for making delay.
I did not do anything special for html header and footer.Actually I have mentioned header, and footer inside phantom property

```
phantom{
"header": Marlin Technologies ",
"footer": "21-08-17"
}
```

I don't know how html page will render this header, and footer property.The thing i need to know is,
Is it possible to make header and footer visible in html rendering?
Else can do it in any other way?
I have already attached my file above comment.

**Comment by bjrmatos** [comment]
> Is it possible to make header and footer visible in html rendering?

i'm afraid that it is not possible, header and footer are special content that it is only visible to the internal phantomjs engine, you best option (and what everybody do) is to change and render again , and keep iterating until you have your desired result. since header/footer content is just html you can also try to render each html in its own (html files) and see the result in your browser but the result will probably be different because layout differences between your actual browser and phantomjs

**Comment by pofider** [comment]
Closing as there is nothing we can do here.
