### ISSUE TITLE
jsreport NSP report updates

### ISSUE THREAD

**Issue by KevinHaisol** [jsreport/jsreport#354]
I ran an nsp check on jsreport.  It looks like there are some security vulnerabilities that need to be fixed.  Any chance these can get the libraries updates to patch the vulnerabilities?

![image](https://user-images.githubusercontent.com/25829792/31677935-ac8e0932-b329-11e7-96cb-c34de7c5aaf9.png)
![image](https://user-images.githubusercontent.com/25829792/31677958-c949f59a-b329-11e7-819e-0a9c19d37a2e.png)
![image](https://user-images.githubusercontent.com/25829792/31677990-e56d9574-b329-11e7-86ac-41ebb0db310f.png)
![image](https://user-images.githubusercontent.com/25829792/31678021-07006ad6-b32a-11e7-89b7-a2356370a1ba.png)
![image](https://user-images.githubusercontent.com/25829792/31678043-19bf3968-b32a-11e7-8721-d41fa411c397.png)

**Comment by bjrmatos** [comment]
hi! the bad thing about `nsp` is that it just does a general check based on dependencies, but it does not take into account if the app is really using feature that is vulnerable. for example see [this conversation](https://github.com/pofider/phantom-html-to-pdf/issues/69) with other user about NSP and false vulnerabilities. i'm just saying this because i'm sure some of the vulnerabilities in the NSP report does not affect jsreport at all and i wanted to highlight that. 

however probably there are some real vulnerabilities in our dependencies that we are actually using so we will take a look and see if this can be solved by just updating some of them.

**Comment by KevinHaisol** [comment]
Thanks,  agreed,  It's usually fairly straight forward with the updates.

**Comment by pofider** [comment]
We have just released the beta version of v2. We tried to update as much dependencies as we could across 100 repositories we maintain. Regardless our affords, the nsp report will always show some errors. 
Please understand that the security warning in such report has for jsreport typically no meaning. It is some kind of vulnerability in one of the 20 000 files jsreport use and in a function jsreport very likely not use at all. These reports are useful rather for libraries which needs to cover all possible vulnerabilities in which it can be used.

Conclusion
We update dependencies regularly during releases and make sure everything works in the stable way.
Don't panic if you see an error in a "security report". It is likely not affecting you and the update of the dependency should come soon. However if you find vulnerability that directly affects jsreport, please let us now via email. Thank you.
