### ISSUE TITLE
Footer not rendering outside jsreport development

### ISSUE THREAD

**Issue by joromeo** [jsreport/jsreport#369]
Hello,

New to JSReport and I am trying to render a report through a web api. Everything renders correctly through the JSReport developer and when I copy everything over to my website's bin directory the footer info is not displaying on the pdf report. I am sure I am missing something but I don't know what.

Thank you.

**Comment by bjrmatos** [comment]
hi! can you explain a little more about your jsreport installation? is it the nodejs jsreport server (installed from npm)? or is it the [.net based](https://jsreport.net/learn/dotnet)? when you copy everything, does jsreport print any warnings or errors in the console? your website directory and your developer environment are in the same machine? or are they different ones? 

instead of manually copying the files you can also start jsreport in your dev environment then use the [export feature](https://jsreport.net/learn/import-export) to get a zip with all your templates, then in the jsreport installation present in your website directory [import the zip file](https://jsreport.net/learn/import-export) and you should get all your templates restored correctly.

**Comment by joromeo** [comment]
Hi!

Should have clarified that. We are using the .net local version integrated into our .net Web API. The jsreport folder (and all corresponding directories) are located in the bin dir of the main application. The calling module is a dll located within the main api site. See dir structure below. 

![image](https://user-images.githubusercontent.com/34318257/33731494-4a2e4dec-db51-11e7-8cae-a72411dfe767.png)

If I try your above mentioned approach the file in the zip is a .json file that has everything compiled into one, not the separate files noted above. Is this the proper deployment for the jsreport files?

**Comment by bjrmatos** [comment]
> If I try your above mentioned approach the file in the zip is a .json file that has everything compiled into one, not the separate files noted above. Is this the proper deployment for the jsreport files?

it is just a way to copy templates, assets, images, basically everything inside `jsreport/data` folder, but it will not copy other files outside that folder.

it is weird that only your footer is not correctly rendered, i'm not 100% sure why it does not work when you deploy your .net website. let's wait for @pofider comments, who knows more than me about the .net part of jsreport.

**Comment by pofider** [comment]
Please make sure you have the latest `jsreport.Binary@1.9.2`. There was issue with headers in the previous one.

**Comment by joromeo** [comment]
Hi and Happy Friday,

Updating the binary package did the trick.

Have a great weekend, appreciate the help!
