### ISSUE TITLE
Can I use jsreport with bootstrap

### ISSUE THREAD

**Issue by kahwooi** [jsreport/jsreport#37]
When I try to generate PDFreport with html and bootstrap, it does not work. 

Can I use stylesheet link when generate a report? Or do I have to write my css inside the html?

**Comment by pofider** [comment]
Yes, you can link external styles with absolute url.

Check it out here https://playground.jsreport.net/#playground/eWCYunp7x/3

You may notice pdf looks different then original html. This is because bootstrap has special styles for printing. You would need to remove or overwrite them to have it the same.

**Comment by kahwooi** [comment]
Thanks. But now I tried to have qr image in the footer, but is not successful:
```
 report.render({
                    template:{
                        content: html,
                        phantom: {
                            footer: '<img src="http://localhost:3000/qr/54a277c1489a4b883b269aa9" height="100" width="100">'
                        }
                    }
                }
```

**Comment by pofider** [comment]
Problems with using bootstrap mentioned in the docs. Closing.
