### ISSUE TITLE
jsreport.render process never exits

### ISSUE THREAD

**Issue by fgiarritiello** [jsreport/jsreport#373]
Hi, I'm using the following code to generate a pdf. I'm using the rendering shortcut because I don't need to run the server since I have a AWS lambda triggering the rendering. However it seems that after the pdf is generated the node process is never exited. What am I doing wrong? Thanks

```const jsreport = require('jsreport');
jsreport.renderDefaults.connectionString = { name: 'fs' };
jsreport.renderDefaults.autoTempCleanup = true;
jsreport.renderDefaults.extensions = ['templates', 'data', 'phantom-pdf', 'handlebars', 'html-to-xlsx', 'scripts', 'text', 'fs-store', 'assets']

function Reporter(options) {
	this.options = options || {};
	return this;
}

Reporter.prototype.createPdf = function(options) {
	console.log('Starting …')

	return jsreport.render({
		template: { shortid: options.templateID },
		data: options.data,
	}).then(function(resp) {
		return resp.content;
	}).catch(function(e) {
		console.log(e)
	})
}

module.exports = Reporter;`

**Comment by bjrmatos** [comment]
hi! in order to the jsreport process to be able to exit normally you are missing two things in your render defaults (configuration):

- if you enable this: `jsreport.renderDefaults.autoTempCleanup = true`, you are telling jsreport that it should create an internal task that periodically should be deleting the temp directory that jsreport is using, this technically creates a timer that prevents the node.js process to exit. in your case you want this to be `jsreport.renderDefaults.autoTempCleanup = false`, i'm not 100% how AWS lambda works but it seems like each run of your AWS lambda will have an isolated temp directory so maybe you won't have the need to worry about temp files cleanup, probably it is handled by AWS itself, so having this option disabled should be safe in the context of AWS lambda.

- when using `fs-store` by default it uses `syncModifications: true` when jsreport is in `development` mode, and since `development` is the default mode is you don't set anything in `NODE_ENV` then the `syncModifications` option is enabled in your case. what `syncModifications: true` does is to create an internal websocket server in order to sync modifications between jsreport studio and file system, in your case you don't need this feature so you can disable it explicitly by using: `jsreport.renderDefaults.connectionString = { name: 'fs', syncModifications: false }`.

update code that exits properly after rendering a report:

```js
jsreport.renderDefaults.connectionString = { name: 'fs', syncModifications: false };
jsreport.renderDefaults.autoTempCleanup = false;
jsreport.renderDefaults.extensions = ['templates', 'data', 'phantom-pdf', 'handlebars', 'html-to-xlsx', 'scripts', 'text', 'fs-store', 'assets']

function Reporter(options) {
	this.options = options || {};
	return this;
}

Reporter.prototype.createPdf = function(options) {
	console.log('Starting …')

	return jsreport.render({
		template: { shortid: options.templateID },
		data: options.data,
	}).then(function(resp) {
		return resp.content;
	}).catch(function(e) {
		console.log(e)
	})
}

module.exports = Reporter;`
```

**Comment by fgiarritiello** [comment]
That worked. You guys are awesome. Thanks
