### ISSUE TITLE
Windows Docker image support

### ISSUE THREAD

**Issue by bloodybeet** [jsreport/jsreport#376]
Hi Jan!

A native Windows Docker image seems missing from this great project. If this is not on the roadmap, we'll probably look into creating this ourselves. What is the current state on this?

**Comment by pofider** [comment]
The windows based image would be great.

I was hoping dockerhub will one day add a support for automated windows based images build, but it seems like it is not coming. Otherwise we need to build and push the images manually every time we release a new version, right? Or would it work to run the build and push through appveyor? Don't you have experience with it?

**Comment by krismeister** [comment]
I'm interested in this too. What is the change needed for a windows docker image?

**Comment by pofider** [comment]
You can create windows docker image just like creating any other windows image.
Just follow the jsreport installation steps for windows.

We will hopefully soon automate it and publish regularly official image to dockerhub.

**Comment by pofider** [comment]
We now ship official docker image based on the windows server core to the dockerhub
https://hub.docker.com/r/jsreport/jsreport/
