### ISSUE TITLE
Problem putting image into footer

### ISSUE THREAD

**Issue by kahwooi** [jsreport/jsreport#38]
I wanted to put a QR image in every page, but it does not show.

Can I insert an image into footer or header?

**Comment by pofider** [comment]
Header is printed to pdf in a synchronous way. This mean any async request like getting image will not finish in time. This is current limitation of phantom.js

Solution 1:
Add the same image to template content and hide it with style display:none. Then you can add it to the header and it will show up because it is already cached and no async request is needed.

Solution 2:
Use base64 encoding and Data URI scheme to embed image directly.

**Comment by pofider** [comment]
Added documentation for this into http://jsreport.net/learn/phantom-pdf

**Comment by Raymond-Does** [comment]
Perhaps useful, when you enter svg data instead of a ref to an image like: `<svg width="100" height="100">
  <circle cx="50" cy="50" r="40" stroke="green" stroke-width="4" fill="yellow" />
</svg>` it will work. I know an svg is not a bitmap but in some cases it might be an option.
