### ISSUE TITLE
Phantom Margin

### ISSUE THREAD

**Issue by zeshanhassan** [jsreport/jsreport#383]
Hi, 
I am using jsreport server 1.92, I am trying to provide custom margin for phantom-pdf. Is there any minimum limit of margin. As I am using 2px but it feels likes, its not working
![image](https://user-images.githubusercontent.com/3735174/36349574-0de6f6c4-14ac-11e8-90f8-2d88788811d0.png)

![image](https://user-images.githubusercontent.com/3735174/36349577-255af044-14ac-11e8-8c87-2afef2da3dd5.png)

is any thing I miss

**Comment by zeshanhassan** [comment]
https://playground.jsreport.net/studio/workspace/SkrDV2UwG/4

**Comment by bjrmatos** [comment]
hi! 

some thing i've seen in your playground link:

- your template does not have the margin options applied
- you have some places with invalid html content in your template, like this `<div class ='table-td sat-td' style="min-width:123px;"'>Saturday</div>` (you should fix your html fix because maybe phantom is just rendering your template in the wrong way because of this, but it is just a recommendation)

i just did a quick test and it seems that there must be some html element or style in your template that makes margin in pixels buggy for phantom. but i've tried with `cm` instead of `px` and it worked, so try to change the unit to `0.8cm` or something like that and adapt to your needs. 

closing the issue because we can't do nothing about the margin behaviour of phantomjs, we just provide the option to specify it. specifying the margin in `cm` should work for you anyway.

**Comment by zeshanhassan** [comment]
this issue is generated on the base phantomjs. you are using phantom 1.8.1 in 1.92
if you update the phantomjs to latest version. the issue related to pixel difference of page is solved

**Comment by bjrmatos** [comment]
the version of phantomjs that comes with jsreport@1.9.2 is phantom 1.9.8, how did you check that you had 1.8.1?

**Comment by zeshanhassan** [comment]
this is the path where file exists
![image](https://user-images.githubusercontent.com/3735174/36479334-15ff75ae-172a-11e8-9888-9b5065d2c387.png)
and from here i get the version 
![image](https://user-images.githubusercontent.com/3735174/36479348-25401f00-172a-11e8-9c42-622eaeefb85a.png)

**Comment by bjrmatos** [comment]
weird, i never saw phantom 1.8.1 being installed on that path (i guess that now it shows 2.1.1 because you updated phantom). anyway glad that you found a solution by just updating.
