### ISSUE TITLE
PhantomJS is being archived

### ISSUE THREAD

**Issue by FernandoAiresCastello** [jsreport/jsreport#390]
Hello, we have recently come across the following issue about PhantomJS: https://github.com/ariya/phantomjs/issues/15344?ct=t(BrazilJS_Weekly_468_9_2013)

It basically states that the project is soon being archived, which made us wondering about the impact it might have on JSReport, since it allows reports to be rendered using PhantomJS. Will it still be supported despite the project being archived?

**Comment by bjrmatos** [comment]
hi! thanks for raising your concerns. we are very aware about phantomjs not being well maintained since some time and we are actively working in jsreport v2 which uses Chrome as the new default (jsreport-phantom-pdf will no longer be part of jsreport by default) recipe for PDF. the v2 beta should be ready soon (a matter of week(s)).



> which made us wondering about the impact it might have on JSReport, since it allows reports to be rendered using PhantomJS. Will it still be supported despite the project being archived?

we don't see jsreport-phantom-pdf going away any time soon (we will always make sure that it works), so you can expect that the recipe based on phantomjs will continue to exists, just that it won't be part of jsreport v2 by default you will need to install it separately in your app if you want to still use it.

**Comment by maisumbruno** [comment]
:+1: :+1: :+1:

**Comment by pofider** [comment]
The jsreport v2 beta is now released and includes chrome instead of phantomjs by default.

https://jsreport.net/blog/jsreport-v2-beta
