### ISSUE TITLE
Error starting jsreport 2.0.0 html-to-xlsx

### ISSUE THREAD

**Issue by brianmtully** [jsreport/jsreport#410]
I get the following error when starting jsreport after upgrading.

2018-05-21T14:14:55.086Z - error: Error when loading extension html-to-xlsx
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.module.exports (/project/node_modules/jsreport-html-to-xlsx/lib/htmlToXl
sx.js:72:43)
    at Object._useOne (/project/node_modules/jsreport-core/lib/extensions/extensionsMa
nager.js:154:75)
    at Object._useMany (/project/node_modules/jsreport-core/lib/extensions/extensionsM
anager.js:73:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by bjrmatos** [comment]
hi! can you provide more details? from which version of jsreport are you upgrading? what were the steps that did you do for upgrading? did you have custom extensions installed in your package.json before upgrading (showing here your original package.json will be better)?

**Comment by brianmtully** [comment]
My dependencies before upgrading are below. I was upgrading from version 1.6.0. I updated the jsreport package and followed the steps to update the config options to match the new format. I never used or installed the html-to-xlsx extension in the previous version. It's pretty much a vanilla install that is crashing.

  "dependencies": {
    "cluster": "0.7.7",
    "jsreport": "1.6.0",
    "jsreport-mongodb-store": "0.5.6",
    "phantomjs-prebuilt": "2.1.14"
  }

**Comment by brianmtully** [comment]
Actually uninstalling phantomjs-prebuilt gets me past the error

**Comment by bjrmatos** [comment]
> Actually uninstalling phantomjs-prebuilt gets me past the error

yes, we found an issue when using the html-to-xlsx extension (which comes with jsreport) at the same time with phantomjs-prebuilt, i have published a hot fix for it, so if you want to still using phantom 2 with `phantomjs-prebuilt` you will need to install the hot fix by using `npm install jsreport-html-to-xlsx@2.0.1 --save`.

about your upgrade to v2, please make sure to check the [breaking changes](https://jsreport.net/learn/v2-breaking-changes), we have changed some things and since you are coming from old version (1.6.0) it is probably that you will need to make some changes in order to have everything working.
