### ISSUE TITLE
Is there a way to use javascript libraries (jquery, angularjs) and their plugins to generate PDF report?

### ISSUE THREAD

**Issue by AhmadMansour** [jsreport/jsreport#421]
Is there a way to use javascript libraries (jquery, angularjs) and their plugins to generate PDF report?
In Jsreport Online services and also Local server

**Comment by bjrmatos** [comment]
yes you can, however remember that in most cases you just need utilities (like charts javascript libraries) and not full frameworks, i would say that using angularjs in a template will be overkill, but it is possible and it is up to you to do it.

you just need to add the js library that you are going to use into the template, to do that you have some options:

- load the js library in a script tag that points to a CDN (like `<script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.6/Chart.min.js'></script>`)

- download the js library from its official site, then upload it into jsreport as an [asset](https://jsreport.net/learn/assets), and finally embed that [asset into your template as a link](https://jsreport.net/learn/assets#embedding-assets-as-links).

then for example when using chrome-pdf, make sure to activate the [js printing trigger](https://jsreport.net/learn/chrome-pdf#printing-triggers) in order to instruct jsreport to wait and start the render only when your code decides it.

finally, [here you have an example that shows the usage of chartjs inside a template](https://playground.jsreport.net/studio/workspace/SkcQLLOGl/869)
