### ISSUE TITLE
jsreport.exe render doesn't apply logging configuration

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#429]
In both v1 and v2 the logger configuration is applied only when the `jsreport exe` is used through `start` command. The `render` command loads the config file, but doesn't apply logger.

**Comment by bjrmatos** [comment]
the explanation for this is the following:

the logger configuration is loaded normally but since [we put the logger in silent mode](https://github.com/jsreport/jsreport-cli/blob/15402f9bc30584143b84cc890d3c4c591dace1ad/lib/instanceHandler.js#L12) to avoid the noise of logs when processing the render command then it may seem that nothing is changed about the logger if you edit logger configuration. so to make the logger do/store something when working with the render command you need to activate the verbose mode `-b` and the logger will work normally.
