### ISSUE TITLE
Send Report(excel or html) to Email .

### ISSUE THREAD

**Issue by A-Pradeep** [jsreport/jsreport#464]
@pofider Hi , right now i'm at stage of getting report form the JSReport server rendered inside the `HTML` like following 
```
jsreport.serverUrl = 'http://loaclhost:5488';
            var request = {
                template: {
                    shortid: "XXXXXX"
                },
                data: data
            };
            jsreport.render(request);      
 };
```

i'll get the response as excel or html based on the template. 

Now i wanted to send this excel or html report  to email based on the `data` which sent in the above code. (like to whom the email to be sent)
I wanted to know whether its possible to achieve this ?

I went through the [online ](https://jsreport.net/learn/periodical-report-sending-through-email) , 
but im confused .

1. 1. Do we need before Render or we can work around only using afterRender . 
2. 2. how to enable `nodemailer` in the JSReport config
3. 3. This smtps `mailer.createTransport('smtps://user%40gmail.com:pass@smtp.gmail.com');` is this the correct syntax `('smtps://emailID:password');`  or i'm giving it wrong .
4. Where should i want to put this code in ! , in the jsreport server or in the html side ?

Thank You.

**Comment by bjrmatos** [comment]
hi!



> 1. Do we need before Render or we can work around only using afterRender .

yes, you can define an script that only has an `afterRender`, in which you can put the email sending logic there



> 1. how to enable `nodemailer` in the JSReport config

you have two ways, if you want to enable all modules not just the specific `nodemailer`, [you can use this config](https://jsreport.net/learn/configuration#allow-local-files-and-local-modules). if you want to enable just `nodemailer`, check the config option needed [here](https://jsreport.net/learn/scripts#use-external-modules)



> 1. This smtps `mailer.createTransport('smtps://user%40gmail.com:pass@smtp.gmail.com');` is this the correct syntax `('smtps://emailID:password');`  or i'm giving it wrong .

it looks fine to me, however since modules like `nodemailer` changes a lot during versions, i would say that it is better that you check what is the correct and updated way to do it by checking the [nodemailer docs](https://nodemailer.com)



> 4\. Where should i want to put this code in ! , in the jsreport server or in the html side ?

it depends on what feels right to you: 

- you can put it in jsreport server script using `afterRender`, then be aware that an email will be send anytime you render that report, however if you have some cases that you will want to just render the report without sending the mail, you can send an additional property in your data that you can use inside the `afterRender` logic to decide if you should send the mail or just skip it.

- the other option you have is to put this email sending logic in your own server code, then after you show the report downloaded in the browser, you can show also some buttons, like send email, that will do a request to your server which should execute the email sending logic.

what of the above ways to use will depend on what feels more appropriate for your case
