### ISSUE TITLE
Error while printing text in PDF

### ISSUE THREAD

**Issue by martinrradev** [jsreport/jsreport#510]
![Screenshot 2019-03-07 at 16 14 33 2](https://user-images.githubusercontent.com/24390880/54119234-834a9200-43fd-11e9-8284-1418ccf6c480.png)

jsreport cli version: 2.03
jsreport version: 2.2.0

Data model is loaded and passed to the template, because all rows and elements (like table) are rendered correctly, however the text is missing in the PDF. Very rarely reproduced - in the JSReport Studio.

Any idea what could be the issue here? 
Thank you.

**Comment by bjrmatos** [comment]
hi! so far i don't see why it should not print any data. if you can share an [import-export](https://jsreport.net/learn/import-export) zip file i can test it and check what can be wrong

**Comment by martinrradev** [comment]
Hi @bjrmatos 

Minimal zip file:
[export.zip](https://github.com/jsreport/jsreport/files/2965128/export.zip)

**Comment by bjrmatos** [comment]
the zip contains the following files:

<img width="159" alt="Captura de pantalla 2019-03-14 a las 10 49 50 a m" src="https://user-images.githubusercontent.com/4262050/54371163-ee3ad980-4646-11e9-9999-5b3c98655c41.png">

but i don't think they are not related to the problem you have.. did you made a mistake when doing the export?

**Comment by martinrradev** [comment]
You're right! My mistake, it's wrong attachment.

Here's the correct one:
[employees.zip](https://github.com/jsreport/jsreport/files/2967391/employees.zip)

**Comment by bjrmatos** [comment]
i can reproduce the problem, i think the problem is expected because chrome tries to convert the page to pdf before the fonts are downloaded, the easy fix is to enable the `wait for network iddle` chrome option in studio.

<img width="205" alt="Captura de pantalla 2019-03-14 a las 5 03 50 p m" src="https://user-images.githubusercontent.com/4262050/54394588-4f7ca000-467b-11e9-9f52-870c2e05e64a.png">

after that the problem is gone for me.
