### ISSUE TITLE
Preview in undocked studio pane loses focus in editor

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#514]
Normally I work in the studio text editor and just use shortcuts ctrl+s or f8 and see the result in the preview pane.
However, if I undock the preview and hit f8, the focus in the editor is lost and I always need to get it back before typing.

**Comment by bjrmatos** [comment]
i tried some methods to make the main window to keep its focus but no luck so far.

- `window.focus()` or `previewWindow.blur()` does not work all, not even with `setTimeout` after some time after the `.open`

- `previewWindow.parent.focus()`, `previewWindow.opener.focus()` does not work too

- `window.open().close()` to try to return focus to the main also does not work.

there are some other things to try but they require to insert some JS in the new windows which we can't do because we execute a form request with the target equal to the new window name which does not give us a chance to add some JS.

**Comment by bjrmatos** [comment]
i was able to make it work by changing the way we store the preview windows 🎉 🎉
