### ISSUE TITLE
pdf digital sign

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#531]
This could be implemented in extra jsreport extension `jsreport-pdf-sign` or something like that.

The studio part would add a new menu to the template if there is a pdf based recipe.
The user would select there an asset - a certificate.

The server part would digitally sign the output in the afterRender in case the output is pdf.
The after render listener should probably use something like `after: pdf-utils, before: scripts`

The implementation would use this package
https://github.com/vbuch/node-signpdf

**Comment by bjrmatos** [comment]
the `signpdf` library works by requiring the pdf to have some kind of [placeholder in the pdf](https://github.com/vbuch/node-signpdf#append-a-signature-placeholder). this is not done automatically by the library which means that we need to this by our own, we need to modify the existing pdf that we have and insert that placeholder. [there is an example in the signpdf repository that shows how to insert the placeholder](https://github.com/vbuch/node-signpdf/blob/develop/src/signpdf.test.js#L43), but it uses pdfkit which won't work in our case because it does not have an api to modify existing PDF. 

what needs to be done is try to find the equivalent methods that the example with `pdfkit` uses, but with `jsreport-pdfjs`, so we can insert the signature placeholder in an existing pdf.

**Comment by pofider** [comment]
This is now ready.
https://jsreport.net/learn/pdf-sign
