### ISSUE TITLE
Runing multiple docker instances of JsReport

### ISSUE THREAD

**Issue by vesamet** [jsreport/jsreport#543]
**Issue:** running two instance of jsreport isn't possible.

**How to reproduce:**
-run one JsReport instance with the default port parameter: `-p 80:5488`
-run another JsReport instance with another open port, ex: `-p 8003:8003` or `-p 8003:5488`.

Also, the port 5488 isn't change when specifying `-p 8003:8003`.

**Comment by bjrmatos** [comment]
it looks like you are using the docker options in wrong way, i just tried and the right way to run two instances is this:

- in one command line run `docker run -p 8003:5488 jsreport/jsreport:2.4.0`
- in another command line run `docker run -p 8004:5488 jsreport/jsreport:2.4.0`
- results in the two servers running at `8003` and `8004` separately



> Also, the port 5488 isn't change when specifying `-p 8003:8003`.

the exposed port of a docker container (in the case of jsreport 5488) won't be changed by using the `-p` option, this is not how docker works. if you want to change or add more exposed ports to a container you need to use the `--expose` option. we expose the 5488 port by default so that is the port that you need to bind to with the `-p` option

**Comment by vesamet** [comment]
I was effectively using the parameter incorrectly. `-p 8003:5488` is working flawlessly.
Thank you !
