### ISSUE TITLE
Using html-xlsx is it possible to add header using <h> tag

### ISSUE THREAD

**Issue by forvy** [jsreport/jsreport#583]
At the moment I was using `<tr><td>Report Test</td></tr>` then style the td but it's not that dynamic. Is it possible to include header tag to be read before `<table>` ?

**Comment by pofider** [comment]
I am afraid I don't understand the question?
Could you please elaborate more and perhaps create [playground](https://playground.jsreport.net) demo?

**Comment by forvy** [comment]
> I am afraid I don't understand the question
> Could you please elaborate more and perhaps create [playground](https://playground.jsreport.net) demo?

Sure, for example [playground](https://playground.jsreport.net/w/anon/7bUx7CCN) notice that I use:
`<tr><td class="header">Report Test</td></tr>` inside `<table>` to treat it as header with style as follow: 
`    .header{
        font-size:35px;
        border-style:none;
    }`

in comparison using:  `<h1>Report Test</h1>` before `<table>` wasn't rendered.

**Comment by bjrmatos** [comment]
ah ok, so you tried to use `<h1>` tag to produce a header.. yes this is not possible at the moment, for now we just convert html table to excel cells, so everything outside won't be converted/adapted into excel cells. but this can be changed in future. i will close this issue, since it just an improvement that we will have in the future, follow #484 for updates about using html elements in html-to-xlsx recipe.
