### ISSUE TITLE
scripts execution for headers

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#657]
The script's execution for child templates and headers is causing confusion for a long time.

We could introduce a new configuration
```js
"scripts": { "executeForChildRequests": false }
```
The `jsreport configure` could create such option even without asking.
In v3 we could default to false.

Another option, for now, is to put checkbox to the studio/script properties.
So the script created in-studio would since then not execute in child requests until checkbox explicitly selected.

**Comment by bjrmatos** [comment]
> ```js
> "scripts": { "executeForChildRequests": false }
> ```

hmm is there a need for handling this as a config? 

i think we can just use the studio checkbox approach and no need for a config, i mean handling this at the template level instead of the extension level.

we can add a checkbox just in the template script properties, and when active all scripts of the template will only run for the template itself, not for the child requests

<img width="210" alt="Captura de pantalla 2019-12-05 a la(s) 5 13 54 p  m" src="https://user-images.githubusercontent.com/4262050/70278716-ca926300-1782-11ea-8b40-3632e78f3a18.png">

this allows the parent template to decide what scripts should be run just for itself, and this approach also allows that rendering a child template which has its own script attached can run based on the child template preference, so basically each template decide if the scripts configured should be run for child or not. 

this means that maybe we can already introduce this checkbox in next version, and it should be false by default for new entities, and when no defined it is assumed to be true, so we handle back compatibility with the way existing templates works

**Comment by pofider** [comment]
Done in 2.7.0
