### ISSUE TITLE
Header/Footer special classes dissapear when i modify style font size

### ISSUE THREAD

**Issue by cdespinosaagmx** [jsreport/jsreport#708]
I'm sending this html to footerTemplate using the jsreport SDK.

`var footer = '<span style="font-size:12px">Page&nbsp;<span class="pageNumber"></span>&nbsp;of&nbsp;<span class="totalPages"></span></span>';`
my code in controller is it:

![image](https://user-images.githubusercontent.com/62155748/76651363-f82d3c00-6529-11ea-8f38-5156e3c6634a.png)

the result after print is this:

![image](https://user-images.githubusercontent.com/62155748/76650845-02026f80-6529-11ea-8285-c59381acb9ca.png)

if i don't add `<span style="font-size:12px">`  to my html footerTemplate it shows the class pageNumber but too small in the PDF, when i try to change the font-size in the html footerTemplate the class pageNumber is not appearing in the PDF, any ideas what it could be?

PD: I'm using the last versión Binary. 2.7.1, i changed it today. When i was using the versión 2.6.1 it was not happening, i had the same code and it was working fine.

**Comment by pofider** [comment]
Thank you.. 
I post here some details we will analyze.
The long store short for you now is to use margin "1.1.cm" instead of "1cm".

With the puppeteer 2.0.0 we use in jsreport 2.7.1 the header template in some cases doesn't display the page number.

I uploaded the test. It doesn't display numbers with jsreport 2.7.1 but works with 2.6.1
Changing the margin from 1cm to 1.1cm helps.
[export (72).zip](https://github.com/jsreport/jsreport/files/4340010/export.72.zip)

I am not sure if this has something to do with this announced change or not.
puppeteer/puppeteer#5080
We will need to find out if we should just ignore it or change some viewport settings somehow.

**Comment by cdespinosaagmx** [comment]
Chaging the margin from 1cm to 1.1cm is working, thanks for your answer!.

**Comment by bjrmatos** [comment]
we investigated and did not found more information about this, so we assume this is an internal change about how the pdf is measured in chrome. changing the viewport does not have any effect. 

this is the new behaviour of recent version of chrome so we can not do anything about it, but in case you find something else let us know.
