### ISSUE TITLE
Error occured during reporter init Error: EACCES: permission denied, mkdir '/app/data/storage'

### ISSUE THREAD

**Issue by adilsoncarvalho** [jsreport/jsreport#728]
Since version `2.7.0` of the docker image is struggling to boot inside a Kubernetes cluster because of the lack of permissions.

```
Error occured during reporter init Error: EACCES: permission denied, mkdir '/app/data/storage'
```

![image](https://user-images.githubusercontent.com/349796/84590417-b50c9d00-ae79-11ea-98e3-e4acace13e99.png)

**Comment by pofider** [comment]
Do you have your own image and inherit from jsreport base image? Do you have the data/templates inside your image?
Or do you mount to /app/data with templates stored externally?

**Comment by adilsoncarvalho** [comment]
Hello @pofider,

I build my own image using `jsreport` image as the base one. I copy into `/app/data` my reports configuration. Here is my `Dockerfile`:

```dockerfile
FROM jsreport/jsreport:2.6.1

COPY . /jsreport

RUN npm i sequelize pg
```

As I mentioned, this error started to show since `2.7.0`, and when I build and run it locally with `docker-compose` it works, but when it tries to run inside Kubernetes, it fails.

Thank you for jumping into this.

**Comment by pofider** [comment]
Thank you for the additional details.
We now use a custom user to start node process inside docker instead of the root user.
This means you need to give the proper permissions to the files you copy to the image.
Like this:
```docker
COPY --chown=jsreport:jsreport . /jsreport
```

Its documented here
https://jsreport.net/learn/docker#customize-docker-image

I close this now, let me know if you need more info.
