### ISSUE TITLE
Review Docker Image Builds

### ISSUE THREAD

**Issue by strigona-worksight** [jsreport/jsreport#757]
Hi, I'd like to suggest reviewing your build process for your docker images. The "default" image is growing in size with every release since it is being built on the previous image. You can see the way the layers are stacking up here:
https://hub.docker.com/layers/jsreport/jsreport/latest/images/sha256-faf9dfed36dad0a129d9ccc563e78ea59da4d1fcb669d7c689780e8ea0e0fa72?context=explore

At the very least, I think it would be more reasonable to base the image on jsreport/jsreport:2.7.2.

**Comment by pofider** [comment]
Thank you for the suggestion. I didn't notice we are growing in size so much.
We are doing "base" on the previous image because the chrome binary we need because of compatibility isn't in the public repos anymore.
The upcoming release v3 will be a major one with the latest chrome binary and this won't be needed.

**Comment by strigona-worksight** [comment]
Ok - sounds good! Feel free to close this.
