### ISSUE TITLE
Report timeout error details

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#837]
When the script hangs, the final error looks like

```
Report "test" render failed.

Report timeout
Error: Report timeout
    at Timeout._onTimeout (C:\work\jsreport\jsreport\packages\advanced-workers\lib\threadWorker.js:41:23)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```

Probably the worker is killed before the sandbox timeouts, needs investigation

**Comment by pofider** [comment]
The VM2 sandbox now doesn't apply timeout. This means if sandbox takes too long the worker thread is killed from the main and poor message "Report timeout" is printed.

The solution:
1. We need to be able to calculate the missing time for the request evaluation and use this for VM2 timeout. The error message should include what entity sandbox evaluation hanged.
2. This is more optional but can work.... The global "Report timeout" message could be decorated with some information from the last running profiler operation.

**Comment by bjrmatos** [comment]
after some investigation here is the conclusion:

we thought that setting the vm2 timeout will correctly handle scripts that just hangs, but that timeout option just works for sync code, the vm2 docs says this:

>IMPORTANT: Timeout is only effective on synchronous code you run through run. Timeout is NOT effective on any method returned by VM. There're some situations when timeout doesn't work

our sandbox is async because we have async execution support there. we tried to investigate some workaround but all goes back to the general timeout handling we have right now, because the vm2 also hangs the process if the script contains `while (true) {}` so the timeout handling that is going to be effective goes back to handling in the main reporter process.

so for now as the solution, we can only work on point number 2
