### ISSUE TITLE
Licensing/Enterprise edition

### ISSUE THREAD

**Issue by dlong500** [jsreport/jsreport#97]
I'm a bit confused about what I'm now seeing on the jsreport.net website.  I'm not sure if it has changed recently, but I don't think I saw before what I'm seeing now.

So there is apparently a 5 template limitation on the "free" edition.  What exactly does that mean?  I thought the jsreport engine was open source?

**Comment by pofider** [comment]
Hi, thanks for the question.

I wanted to clarify it in the readme and blog, just didn't get to it yet.

Yes, this is the recent change and this is how I try to get funding for the future jsreport development and maintenance. The incomes from consulting covers less than 1% and after two years of full time I drained the most of my savings. Thus there is no other way if I want to continue with it and also grow the team behind it.

Please understand that open source doesn't mean free. It is common practice to monetize open source software this way. You can check also popular libraries on github like [highcharts.js](https://github.com/highslide-software/highcharts.com) or [ravendb](https://github.com/ravendb/ravendb) with the similar models.  

I have put a lot of effort into the openness of jsreport and through the time released very significant part of jsreport with free copyleft MIT license. All of the following libraries used by jsreport can be modified  and distributed without any limitations:

https://github.com/jsreport/toner
https://github.com/jsreport/toner-phantom
https://github.com/jsreport/toner-html-to-xlsx
https://github.com/jsreport/toner-wkhtmltopdf
https://github.com/jsreport/toner-jsrender
https://github.com/jsreport/toner-handlebars

https://github.com/pofider/html-to-xlsx
https://github.com/pofider/node-script-manager
https://github.com/pofider/node-simple-odata-server
https://github.com/pofider/phantom-html-to-pdf
https://github.com/pofider/phantom-workers
https://github.com/pofider/node-wkhtmltopdf-installer

Also the pricing model is the friendliest as it could be. The small projects rendering just an invoice are free to use it without enterprise license. The price for the enterprise is 10% of price of the compared products.

The switch to this different licensing model was morally and legally possible because I am anyway the only (significant) contributor to this repository. The future contributors will just need to sign with us an contribution agreement.

Thank you for your understanding

**Comment by dlong500** [comment]
I know as the author of the code you have the right to change licensing models for future releases, but it just took me by surprise because I was under the impression the entire jsreport ecosystem was both free and open source being hosted publicly on Github, and that only the hosted "jsreport online" service had a cost.

Honestly I haven't been using more than the toner modules at this point anyway, but if I chose to go with the full jsreport server at some point I can easily see needing more than 5 templates even for a relatively small project.

What is involved in getting the free enterprise license mentioned for being a contributor?  To what extent would one need to contribute?  And what if I'm working on multiple projects?

Thanks.

**Comment by pofider** [comment]
Yes, you had the right impression, it was just changed for the mentioned reasons. 

Toner is MIT licensed so you can do whatever you want with it. This is my gift to node.js community. 

It would be maybe better to limit the free license rather with amount of the rendered reports. Let say that you can render 1000 reports a month with free license. I will think about it.

This cannot be specified or measured exactly. But lets say I release 1 license for every 1-2 days spent on helping jsreport to become better. Improving official documentation, bug fixing, external blog post, screen cast, new feature development a new custom extension... There are tons of things which can be improved. My intention is really to keep moving jsreport ecosystem forward.

**Comment by bjrmatos** [comment]
@pofider What about starting a [patreon](https://www.patreon.com/) campaign?

i think licensing jsreport could affect adoption of the library, but i understand your reasons..

you could try to create a campaign and see how it ends, and based on the results decide what is best for jsreport.

see https://www.patreon.com/reactdx?ty=h as an example of a success campaign :smiley: 

I **really** love your project, thnks for your hard work :clap:

**Comment by araczkowski** [comment]
Hi,
I completely understand the @pofider position, and I hope that he will be able to monetize the jsreport somehow.
I have some reporting background and the solution implemented in jsreport is really great - I see the potential and I'm trying to convince some of my Clients to use this solution.

But in other hand when I read the discussion I'm starting to have a doubts concerning the "switch to this different licensing model" ...
**My main question/doubt is -> if the jsreport will stay under the GNU GPLv3?**


@pofider **could you please confirm that my understanding of jsreport licensing below is correct or not?**
Thank you in advance.


**My assumptions (if I correctly understand this topic):**
1. The jsreport is based on many OpenSource components
2. It is released under GNU GPLv3,
3. The licence for the code source(http://jsreport.net/blog/licensing) was not changed from the beginning of the project and it's not changing now. 


**What this means is:**
1. @pofider can **distribute jsreport for profit** (sell the transfer/distrubution and support), 
2. @pofider **can NOT sell the right to use the sources of jsreport**, 
you can NOT just say -> no payment == no right to use a jsreport sources. 
The goal of the GPL is to grant everyone the freedom to copy, distribute, understand, and modify a program. Linus Torvalds can't sell the right to use a sources of the Linux too.
3. If @pofider (or anybody else) will change the source code to the program and give/sell (the "binary"/working version of the program) to 3rd" parties you must also give access to the modified source.


**The conclusion for me:**
(lets assume the hypothetical situation)
1. I legally used jsreport in the project,
2. I can (has a right to) change/improve the jsreport code 
(after this according to the licence of course I need to give access to the modified source code),
3. Additionally I can distribute my version (sell the transfer/distrubution and support).

**Comment by pofider** [comment]
I am very thankful for your inputs and comments.

@bjrmatos 
These campaigns works only for products having "global impact" in my opinion and even then the ROI is very low. 

@araczkowski 
If it is GPL licensed your logic is correct. 

I am proposing the following:

jsreport will no longer be GPL but "no licensed". This means it stays open on github, users can download it, use it and modify it for their own purpose. There will be certain limitations in the code like "max 5 templates" unlocked by enterprise license. You can easily skip the warning for the missing license, but enterprises will anyway rather buy it.

During the time I will be able to use the funding from enterprise licenses to grow jsreport and implement more advanced features. The repository would be split then into the free GPL licensed jsreport and commercially licensed enterprise features. This would be the desired future.

I hope the period without GPL won't block your plans with jsreport. Anyway the most of the jsreport is pluggable extension therefore you should be able to implement, monetize and distribute your custom features as you need.

What do you think?

**Comment by bjrmatos** [comment]
seems fine to me, this would mean that the free GPL licensed version of jsreport won't have any limitations? (like max 5 templates) and enterprise licensed will only have more advanced features?

right now i wanna focus in learn jsreport's codebase and hope to contribute soon (if you have some kind of roadmap, let us know).

**Comment by pofider** [comment]
@bjrmatos Yes exactly. I would like jsreport to be GPL licensed, free, without limitations and with growing list of extensions and contributors. I would then just sell some additional enterprise features and support. I only need some time and funding to get there. Without this step it won't grow.

I clarified this in the readme and also on the [website blog](http://jsreport.net/blog/updated-licensing). I hope we fulfill the plan soon.

**Comment by bjrmatos** [comment]
:tada: thnk you again :clap:

**Comment by araczkowski** [comment]
Hi,

sorry for long reply time - vacations :)

I'm glad that there is a plan for the future to back to GPL licence for the server and sell additional features and support. 
In my opinion it would be a better way to grow the project so I hope that you will be able to re-change the licence back soon.

**Concerning the period without GPL and my plans with jsreport**:

The case is that I trust the GPL and I like the freedom which give this kind of open licenses. 
In my opinion the free licence was the biggest (not technical) advantage of this project -> no vendor/proprietary lock-in solution.
Please don't get me wrong - I don't mind to pay for support or/and for the advanced feature, the price is very reasonable. But when the code is proprietary you can always (in the future) do another pivot for your business model or just sell the project... Of course I fully respect your decision - you have the full right to do this.

But to cover my needs I'm going to:
1. fork jsreport v0.7.2 (the GPL version of the code)
2. I will change the name and logo to something else - to avoid confusion
3. I will adapt it to my special needs 
4. of course I will keep it under GPL and it will be available in my public repo

@pofider
**In my opinion this will be fully legal but to be sure I want to ask -> Is this OK for you?**

**Comment by pofider** [comment]
@araczkowski
Sure, go ahead, you have the right to do it. I am even happy for it as long as you don't plan to make another copy of jsreport. Please let me know when you find some interesting use cases or improvements.

GPL based project grows faster, but monetizing model based on support turned out to be insufficient after two years of my full time and zero incomes. :) I just need to prepare for selling  enterprise features and then switch back to GPL for the last time. Please don't panic until then, you can still use older version for free without limits.

I guess this is all clear now. I would really appreciate your help with implementation or feature suggestions, please continue to be active here. Thank you.
