### ISSUE TITLE
profiling error

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#979]
The following errors from `jsreportonline` indicates `req.context.profiling` isn't initialized.
However, I don't see how that could happen. It's initialized at the very beginning of the `reporter.render`.

```
TypeError: Cannot set properties of undefined (setting 'lastOperation')
    at emitProfiles (/usr/src/app/node_modules/@jsreport/jsreport-core/lib/main/profiler.js:104:43)
    at /usr/src/app/node_modules/@jsreport/jsreport-core/lib/main/profiler.js:138:12
    at MainReporter._invokeMainAction (/usr/src/app/node_modules/@jsreport/jsreport-core/lib/main/reporter.js:540:50)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
 ```
    
```    
TypeError: Cannot read properties of undefined (reading 'mode')
    at runInProfilerChain (/usr/src/app/node_modules/@jsreport/jsreport-core/lib/main/profiler.js:29:31)
    at emitProfiles (/usr/src/app/node_modules/@jsreport/jsreport-core/lib/main/profiler.js:107:5)
    at /usr/src/app/node_modules/@jsreport/jsreport-core/lib/main/profiler.js:138:12
    at MainReporter._invokeMainAction (/usr/src/app/node_modules/@jsreport/jsreport-core/lib/main/reporter.js:540:50)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5
```

@bjrmatos I have no theory, don't you? It is most likely a remote/cross-worker request based on the logs, but I don't see a reason that should have an impact.

**Comment by bjrmatos** [comment]
hmm i also think it is something about the remote requests, perhaps some kind of async report or schedule may trigger it? we do [this](https://github.com/jsreport/jsreport/commit/c41b3d36828e4895436f94b97ee2b9f6624e7e79) to support the profiling in remote request. 

the idea is that at the very beginning on the main server [we store the original jsreport request object](https://github.com/jsreport/jsreport/commit/c41b3d36828e4895436f94b97ee2b9f6624e7e79#diff-552b95230de23e9c29eccca02fd3993e0a08b7704f0e8b2c8b647af5192232c4R223) we do this because in the remote server requests the profiling events do not happen in this server, and when we propagate such events from the remote server we want to emit the logs against a jsreport request object, we use this request object store [here](https://github.com/jsreport/jsreport/commit/c41b3d36828e4895436f94b97ee2b9f6624e7e79#diff-552b95230de23e9c29eccca02fd3993e0a08b7704f0e8b2c8b647af5192232c4R125). when the profile in the remote server happens we [propagate the data produced there to the main server](https://github.com/jsreport/jsreport/commit/c41b3d36828e4895436f94b97ee2b9f6624e7e79#diff-3cc23d9a37a89b2d3adca5aefa258b3463b6570e48619ad4cf136f1a48d60a1aR116), so the main server can stream the logs to the connection the user has with studio. 

what i think it is happening somehow the request object stored [here](https://github.com/jsreport/jsreport/commit/c41b3d36828e4895436f94b97ee2b9f6624e7e79#diff-552b95230de23e9c29eccca02fd3993e0a08b7704f0e8b2c8b647af5192232c4R223) at that specific beforeRender event does not have yet the profiling initialized but that is also weird.

**Comment by pofider** [comment]
I give up on this for now and just summarize what I discovered and wait for the next occurrence to help us better locate the cause.

The error happened in this situation:
3 parallel requests for one tenant (2 local and 1 remote)
The remote has some syntax sandbox user error
One local finishes fine
Second local causes the profiler error.

The strange thing is that I see 3 parallel requests reaching the worker execution and logging "Rendering template...", when this shouldn't happen at all because we have just 2 workers.

**Comment by pofider** [comment]
The error was spotted again at the same time when we were creating nodejs dump.
This is a blocking process so perhaps it has something to do with the blocked event loopl.
However, no testing locally or in test env revealed the error again.

**Comment by pofider** [comment]
This should be already fixed.
